package ibp.repository.dao;

import ibp.repository.model.IbpIfCcbTxn;
import ibp.repository.model.IbpIfCcbTxnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IbpIfCcbTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int countByExample(IbpIfCcbTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int deleteByExample(IbpIfCcbTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int insert(IbpIfCcbTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int insertSelective(IbpIfCcbTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    List<IbpIfCcbTxn> selectByExample(IbpIfCcbTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    IbpIfCcbTxn selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") IbpIfCcbTxn record, @Param("example") IbpIfCcbTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int updateByExample(@Param("record") IbpIfCcbTxn record, @Param("example") IbpIfCcbTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int updateByPrimaryKeySelective(IbpIfCcbTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_CCB_TXN
     *
     * @mbggenerated Fri Oct 31 17:20:10 CST 2014
     */
    int updateByPrimaryKey(IbpIfCcbTxn record);
}