package ibp.repository.dao;

import ibp.repository.model.IbpIfNetbnkTxn;
import ibp.repository.model.IbpIfNetbnkTxnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IbpIfNetbnkTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int countByExample(IbpIfNetbnkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int deleteByExample(IbpIfNetbnkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int insert(IbpIfNetbnkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int insertSelective(IbpIfNetbnkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    List<IbpIfNetbnkTxn> selectByExample(IbpIfNetbnkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    IbpIfNetbnkTxn selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") IbpIfNetbnkTxn record, @Param("example") IbpIfNetbnkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int updateByExample(@Param("record") IbpIfNetbnkTxn record, @Param("example") IbpIfNetbnkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int updateByPrimaryKeySelective(IbpIfNetbnkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_NETBNK_TXN
     *
     * @mbggenerated Wed Mar 25 09:04:33 CST 2015
     */
    int updateByPrimaryKey(IbpIfNetbnkTxn record);
}