package ibp.repository.dao;

import ibp.repository.model.IbpIfUnionpayTxn;
import ibp.repository.model.IbpIfUnionpayTxnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IbpIfUnionpayTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int countByExample(IbpIfUnionpayTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int deleteByExample(IbpIfUnionpayTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int insert(IbpIfUnionpayTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int insertSelective(IbpIfUnionpayTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    List<IbpIfUnionpayTxn> selectByExample(IbpIfUnionpayTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    IbpIfUnionpayTxn selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int updateByExampleSelective(@Param("record") IbpIfUnionpayTxn record, @Param("example") IbpIfUnionpayTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int updateByExample(@Param("record") IbpIfUnionpayTxn record, @Param("example") IbpIfUnionpayTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int updateByPrimaryKeySelective(IbpIfUnionpayTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_IF_UNIONPAY_TXN
     *
     * @mbggenerated Mon Dec 01 11:23:54 CST 2014
     */
    int updateByPrimaryKey(IbpIfUnionpayTxn record);
}