package ibp.repository.dao;

import ibp.repository.model.IbpJshOrder;
import ibp.repository.model.IbpJshOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IbpJshOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    int countByExample(IbpJshOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    int deleteByExample(IbpJshOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    int insert(IbpJshOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    int insertSelective(IbpJshOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    List<IbpJshOrder> selectByExample(IbpJshOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") IbpJshOrder record, @Param("example") IbpJshOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.IBP_JSH_ORDER
     *
     * @mbggenerated Tue Apr 21 16:16:32 CST 2015
     */
    int updateByExample(@Param("record") IbpJshOrder record, @Param("example") IbpJshOrderExample example);
}