package ibp.repository.dao;

import ibp.repository.model.IbpSbsact;
import ibp.repository.model.IbpSbsactExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;

@Component
public interface IbpSbsactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    int countByExample(IbpSbsactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    int deleteByExample(IbpSbsactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    int insert(IbpSbsact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    int insertSelective(IbpSbsact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    List<IbpSbsact> selectByExample(IbpSbsactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") IbpSbsact record, @Param("example") IbpSbsactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.IBP_SBSACT
     *
     * @mbggenerated Wed Nov 05 11:11:35 CST 2014
     */
    int updateByExample(@Param("record") IbpSbsact record, @Param("example") IbpSbsactExample example);

    @Select(" select pkid, actnum, actnam, status, opndat from IBP_SBSACT t " +
            " where t.actnam like #{act} and " +
            " ( t.ACTNUM like '%2017001' or t.ACTNUM like '%2033001' or t.ACTNUM like '%2301001')")
    List<IbpSbsact> qrySbsactToTrans(@Param("act") String act);
}