package fip.repository.dao;

import fip.repository.model.Fdactnoinfo;
import fip.repository.model.FdactnoinfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FdactnoinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int countByExample(FdactnoinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int deleteByExample(FdactnoinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int deleteByPrimaryKey(String contractno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int insert(Fdactnoinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int insertSelective(Fdactnoinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    List<Fdactnoinfo> selectByExample(FdactnoinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    Fdactnoinfo selectByPrimaryKey(String contractno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int updateByExampleSelective(@Param("record") Fdactnoinfo record, @Param("example") FdactnoinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int updateByExample(@Param("record") Fdactnoinfo record, @Param("example") FdactnoinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int updateByPrimaryKeySelective(Fdactnoinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FDACTNOINFO
     *
     * @mbggenerated Sat Aug 13 11:53:11 CST 2011
     */
    int updateByPrimaryKey(Fdactnoinfo record);
}