package fip.repository.dao;

import fip.repository.model.FipCutpaybat;
import fip.repository.model.FipCutpaybatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface FipCutpaybatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int countByExample(FipCutpaybatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int deleteByExample(FipCutpaybatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int deleteByPrimaryKey(String txpkgSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int insert(FipCutpaybat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int insertSelective(FipCutpaybat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    List<FipCutpaybat> selectByExample(FipCutpaybatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    FipCutpaybat selectByPrimaryKey(String txpkgSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") FipCutpaybat record, @Param("example") FipCutpaybatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int updateByExample(@Param("record") FipCutpaybat record, @Param("example") FipCutpaybatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int updateByPrimaryKeySelective(FipCutpaybat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYBAT
     *
     * @mbggenerated Fri Apr 17 15:26:45 CST 2015
     */
    int updateByPrimaryKey(FipCutpaybat record);
}