package fip.repository.dao;

import fip.repository.model.FipCutpaydetl;
import fip.repository.model.FipCutpaydetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FipCutpaydetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int countByExample(FipCutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int deleteByExample(FipCutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int insert(FipCutpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int insertSelective(FipCutpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    List<FipCutpaydetl> selectByExample(FipCutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    FipCutpaydetl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByExampleSelective(@Param("record") FipCutpaydetl record, @Param("example") FipCutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByExample(@Param("record") FipCutpaydetl record, @Param("example") FipCutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByPrimaryKeySelective(FipCutpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_CUTPAYDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByPrimaryKey(FipCutpaydetl record);
}