package fip.repository.dao;

import fip.repository.model.FipInterbankinfo;
import fip.repository.model.FipInterbankinfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FipInterbankinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int countByExample(FipInterbankinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int deleteByExample(FipInterbankinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int insert(FipInterbankinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int insertSelective(FipInterbankinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    List<FipInterbankinfo> selectByExample(FipInterbankinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    FipInterbankinfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int updateByExampleSelective(@Param("record") FipInterbankinfo record, @Param("example") FipInterbankinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int updateByExample(@Param("record") FipInterbankinfo record, @Param("example") FipInterbankinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int updateByPrimaryKeySelective(FipInterbankinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_INTERBANKINFO
     *
     * @mbggenerated Tue Sep 06 15:51:04 CST 2011
     */
    int updateByPrimaryKey(FipInterbankinfo record);
}