package fip.repository.dao;

import fip.repository.model.FipJoblog;
import fip.repository.model.FipJoblogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FipJoblogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    int countByExample(FipJoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    int deleteByExample(FipJoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    int insert(FipJoblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    int insertSelective(FipJoblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    List<FipJoblog> selectByExample(FipJoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    int updateByExampleSelective(@Param("record") FipJoblog record, @Param("example") FipJoblogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_JOBLOG
     *
     * @mbggenerated Mon Aug 15 09:53:34 CST 2011
     */
    int updateByExample(@Param("record") FipJoblog record, @Param("example") FipJoblogExample example);
}