package fip.repository.dao;

import fip.repository.model.FipPayoutbat;
import fip.repository.model.FipPayoutbatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FipPayoutbatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int countByExample(FipPayoutbatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int deleteByExample(FipPayoutbatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int insert(FipPayoutbat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int insertSelective(FipPayoutbat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    List<FipPayoutbat> selectByExample(FipPayoutbatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    FipPayoutbat selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int updateByExampleSelective(@Param("record") FipPayoutbat record, @Param("example") FipPayoutbatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int updateByExample(@Param("record") FipPayoutbat record, @Param("example") FipPayoutbatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int updateByPrimaryKeySelective(FipPayoutbat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTBAT
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    int updateByPrimaryKey(FipPayoutbat record);
}