package fip.repository.dao;

import fip.repository.model.FipPayoutSbsacts;
import fip.repository.model.FipPayoutSbsactsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FipPayoutSbsactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int countByExample(FipPayoutSbsactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int deleteByExample(FipPayoutSbsactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int insert(FipPayoutSbsacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int insertSelective(FipPayoutSbsacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    List<FipPayoutSbsacts> selectByExample(FipPayoutSbsactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    FipPayoutSbsacts selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int updateByExampleSelective(@Param("record") FipPayoutSbsacts record, @Param("example") FipPayoutSbsactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int updateByExample(@Param("record") FipPayoutSbsacts record, @Param("example") FipPayoutSbsactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int updateByPrimaryKeySelective(FipPayoutSbsacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUT_SBSACTS
     *
     * @mbggenerated Wed May 22 17:28:01 CST 2013
     */
    int updateByPrimaryKey(FipPayoutSbsacts record);
}