package fip.repository.dao;

import fip.repository.model.FipPayoutdetl;
import fip.repository.model.FipPayoutdetlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FipPayoutdetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int countByExample(FipPayoutdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int deleteByExample(FipPayoutdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int insert(FipPayoutdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int insertSelective(FipPayoutdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    List<FipPayoutdetl> selectByExample(FipPayoutdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    FipPayoutdetl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int updateByExampleSelective(@Param("record") FipPayoutdetl record, @Param("example") FipPayoutdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int updateByExample(@Param("record") FipPayoutdetl record, @Param("example") FipPayoutdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int updateByPrimaryKeySelective(FipPayoutdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_PAYOUTDETL
     *
     * @mbggenerated Fri May 17 11:36:21 CST 2013
     */
    int updateByPrimaryKey(FipPayoutdetl record);
}