package fip.repository.dao;

import fip.repository.model.FipRefunddetl;
import fip.repository.model.FipRefunddetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface FipRefunddetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int countByExample(FipRefunddetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int deleteByExample(FipRefunddetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int insert(FipRefunddetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int insertSelective(FipRefunddetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    List<FipRefunddetl> selectByExample(FipRefunddetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    FipRefunddetl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByExampleSelective(@Param("record") FipRefunddetl record, @Param("example") FipRefunddetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByExample(@Param("record") FipRefunddetl record, @Param("example") FipRefunddetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByPrimaryKeySelective(FipRefunddetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.FIP_REFUNDDETL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    int updateByPrimaryKey(FipRefunddetl record);
}