package fip.repository.dao;

import fip.repository.model.Xfactcutpaymain;
import fip.repository.model.XfactcutpaymainExample;
import fip.repository.model.XfactcutpaymainKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XfactcutpaymainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfactcutpaymainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfactcutpaymainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(XfactcutpaymainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfactcutpaymain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfactcutpaymain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfactcutpaymain> selectByExample(XfactcutpaymainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xfactcutpaymain selectByPrimaryKey(XfactcutpaymainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfactcutpaymain record, @Param("example") XfactcutpaymainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfactcutpaymain record, @Param("example") XfactcutpaymainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xfactcutpaymain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYMAIN
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xfactcutpaymain record);
}