package fip.repository.dao;

import fip.repository.model.Xfactpaydetl;
import fip.repository.model.XfactpaydetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XfactpaydetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfactpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfactpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(String journalno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfactpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfactpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfactpaydetl> selectByExample(XfactpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xfactpaydetl selectByPrimaryKey(String journalno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfactpaydetl record, @Param("example") XfactpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfactpaydetl record, @Param("example") XfactpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xfactpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xfactpaydetl record);
}