package fip.repository.dao;

import fip.repository.model.Xfactcutpaydetl;
import fip.repository.model.XfactcutpaydetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface XfactcutpaydetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfactcutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfactcutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(String journalno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfactcutpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfactcutpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfactcutpaydetl> selectByExample(XfactcutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xfactcutpaydetl selectByPrimaryKey(String journalno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfactcutpaydetl record, @Param("example") XfactcutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfactcutpaydetl record, @Param("example") XfactcutpaydetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xfactcutpaydetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFACTCUTPAYDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xfactcutpaydetl record);
}