package fip.repository.dao;

import fip.repository.model.Xfappadd;
import fip.repository.model.XfappaddExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface XfappaddMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int countByExample(XfappaddExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int deleteByExample(XfappaddExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int deleteByPrimaryKey(String appno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int insert(Xfappadd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int insertSelective(Xfappadd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    List<Xfappadd> selectByExample(XfappaddExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    Xfappadd selectByPrimaryKey(String appno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfappadd record, @Param("example") XfappaddExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByExample(@Param("record") Xfappadd record, @Param("example") XfappaddExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByPrimaryKeySelective(Xfappadd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPADD
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByPrimaryKey(Xfappadd record);
}