package fip.repository.dao;

import fip.repository.model.Xfapprepayment;
import fip.repository.model.XfapprepaymentExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface XfapprepaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int countByExample(XfapprepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int deleteByExample(XfapprepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int deleteByPrimaryKey(String appno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int insert(Xfapprepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int insertSelective(Xfapprepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    List<Xfapprepayment> selectByExample(XfapprepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    Xfapprepayment selectByPrimaryKey(String appno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfapprepayment record, @Param("example") XfapprepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int updateByExample(@Param("record") Xfapprepayment record, @Param("example") XfapprepaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int updateByPrimaryKeySelective(Xfapprepayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    int updateByPrimaryKey(Xfapprepayment record);
}