package fip.repository.dao;

import fip.repository.model.Xfappcommbatch;
import fip.repository.model.XfappcommbatchExample;
import fip.repository.model.XfappcommbatchKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface XfappcommbatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int countByExample(XfappcommbatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int deleteByExample(XfappcommbatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int deleteByPrimaryKey(XfappcommbatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int insert(Xfappcommbatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int insertSelective(Xfappcommbatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    List<Xfappcommbatch> selectByExample(XfappcommbatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    Xfappcommbatch selectByPrimaryKey(XfappcommbatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfappcommbatch record, @Param("example") XfappcommbatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByExample(@Param("record") Xfappcommbatch record, @Param("example") XfappcommbatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByPrimaryKeySelective(Xfappcommbatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMMBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByPrimaryKey(Xfappcommbatch record);
}