package fip.repository.dao;

import fip.repository.model.Xfclient;
import fip.repository.model.XfclientExample;
import fip.repository.model.XfclientKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface XfclientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int countByExample(XfclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int deleteByExample(XfclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int deleteByPrimaryKey(XfclientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int insert(Xfclient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int insertSelective(Xfclient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    List<Xfclient> selectByExample(XfclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    Xfclient selectByPrimaryKey(XfclientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfclient record, @Param("example") XfclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int updateByExample(@Param("record") Xfclient record, @Param("example") XfclientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int updateByPrimaryKeySelective(Xfclient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCLIENT
     *
     * @mbggenerated Tue Aug 16 17:12:08 CST 2011
     */
    int updateByPrimaryKey(Xfclient record);
}