package fip.repository.dao;

import fip.repository.model.Xfcontractpays;
import fip.repository.model.XfcontractpaysExample;
import fip.repository.model.XfcontractpaysKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XfcontractpaysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfcontractpaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfcontractpaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(XfcontractpaysKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfcontractpays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfcontractpays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfcontractpays> selectByExample(XfcontractpaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xfcontractpays selectByPrimaryKey(XfcontractpaysKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfcontractpays record, @Param("example") XfcontractpaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfcontractpays record, @Param("example") XfcontractpaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xfcontractpays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACTPAYS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xfcontractpays record);
}