package fip.repository.dao;

import fip.repository.model.Xfcontract;
import fip.repository.model.XfcontractExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XfcontractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(String contractno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfcontract> selectByExample(XfcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xfcontract selectByPrimaryKey(String contractno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfcontract record, @Param("example") XfcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfcontract record, @Param("example") XfcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xfcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFCONTRACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xfcontract record);
}