package fip.repository.dao;

import fip.repository.model.Xfcreditinfobatch;
import fip.repository.model.XfcreditinfobatchExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface XfcreditinfobatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int countByExample(XfcreditinfobatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int deleteByExample(XfcreditinfobatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int deleteByPrimaryKey(String appno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int insert(Xfcreditinfobatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int insertSelective(Xfcreditinfobatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    List<Xfcreditinfobatch> selectByExample(XfcreditinfobatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    Xfcreditinfobatch selectByPrimaryKey(String appno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfcreditinfobatch record, @Param("example") XfcreditinfobatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByExample(@Param("record") Xfcreditinfobatch record, @Param("example") XfcreditinfobatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByPrimaryKeySelective(Xfcreditinfobatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFCREDITINFOBATCH
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    int updateByPrimaryKey(Xfcreditinfobatch record);
}