package fip.repository.dao;

import fip.repository.model.Xffeeinfo;
import fip.repository.model.XffeeinfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XffeeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XffeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XffeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xffeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xffeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xffeeinfo> selectByExample(XffeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xffeeinfo selectByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xffeeinfo record, @Param("example") XffeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xffeeinfo record, @Param("example") XffeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xffeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFFEEINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xffeeinfo record);
}