package fip.repository.dao;

import fip.repository.model.Xfgrademark;
import fip.repository.model.XfgrademarkExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;

@Component

public interface XfgrademarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfgrademarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfgrademarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByPrimaryKey(BigDecimal seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfgrademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfgrademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfgrademark> selectByExample(XfgrademarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    Xfgrademark selectByPrimaryKey(BigDecimal seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfgrademark record, @Param("example") XfgrademarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfgrademark record, @Param("example") XfgrademarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKeySelective(Xfgrademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFGRADEMARK
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByPrimaryKey(Xfgrademark record);
}