package fip.repository.dao;

import fip.repository.model.Xfifbankdetl;
import fip.repository.model.XfifbankdetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XfifbankdetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfifbankdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfifbankdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfifbankdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfifbankdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfifbankdetl> selectByExampleWithBLOBs(XfifbankdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfifbankdetl> selectByExample(XfifbankdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfifbankdetl record, @Param("example") XfifbankdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") Xfifbankdetl record, @Param("example") XfifbankdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfifbankdetl record, @Param("example") XfifbankdetlExample example);
}