package fip.repository.dao;

import fip.repository.model.Xfwriteoffinfo;
import fip.repository.model.XfwriteoffinfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface XfwriteoffinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int countByExample(XfwriteoffinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int deleteByExample(XfwriteoffinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insert(Xfwriteoffinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int insertSelective(Xfwriteoffinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    List<Xfwriteoffinfo> selectByExample(XfwriteoffinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExampleSelective(@Param("record") Xfwriteoffinfo record, @Param("example") XfwriteoffinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    int updateByExample(@Param("record") Xfwriteoffinfo record, @Param("example") XfwriteoffinfoExample example);
}