package fip.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class FipCutpaydetl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BATCH_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String batchSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BATCH_DETL_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String batchDetlSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.TXPKG_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String txpkgSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.TXPKG_DETL_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String txpkgDetlSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.XFAPP_PKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String xfappPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.APPNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String appno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.IOUNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String iouno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.POANO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String poano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.CONTRACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String contractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.CLIENTNAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String clientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.CLIENTACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String clientact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PAYBACKAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal paybackamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PAYBACKDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String paybackdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.RECVACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String recvact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.RECVBANKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String recvbankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.RECVBANKNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String recvbankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.STARTDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BILLSTATUS
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String billstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PAIDUPAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal paidupamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PAIDUPDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String paidupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PRINCIPALAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal principalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.INTERESTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal interestamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.PUNITIVEINTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal punitiveintamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BREAKAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal breakamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.COMPOUNDINTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal compoundintamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.RESERVEAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private BigDecimal reserveamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BILLTYPE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String billtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.CLIENTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String clientno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.CLIENTIDTYPE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String clientidtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.CLIENTID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biActopeningbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_BANKACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biBankactno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK_UD
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biActopeningbankUd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_BANKACTNAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biBankactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_CUSTOMER_CODE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biCustomerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_SIGN_ACCOUNT_NO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biSignAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_CHANNEL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_PROVINCE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.BI_CITY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String biCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.TX_RETCODE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String txRetcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.TX_RETMSG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String txRetmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.ORIGIN_BIZID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String originBizid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.SENDFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String sendflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.ARCHIVEFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String archiveflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.DELETEDFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String deletedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.RECVERSION
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private Long recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.MERCHANT_NAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.MERCHANT_ACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String merchantActno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.DATE_CMS_GET
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private Date dateCmsGet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.DATE_BANK_CUTPAY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private Date dateBankCutpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.DATE_SBS_ACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private Date dateSbsAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.DATE_CMS_PUT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private Date dateCmsPut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.USER_CMS_GET
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String userCmsGet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.USER_BANK_CUTPAY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String userBankCutpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.USER_SBS_ACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String userSbsAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.USER_CMS_PUT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String userCmsPut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.SBS_INTERBANK_ACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String sbsInterbankActno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.REMARK1
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.REMARK2
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.REMARK3
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String remark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.WRITEBACKFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String writebackflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_CUTPAYDETL.ACCOUNTFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    private String accountflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PKID
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PKID
     *
     * @param pkid the value for FIP.FIP_CUTPAYDETL.PKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BATCH_SN
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BATCH_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBatchSn() {
        return batchSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BATCH_SN
     *
     * @param batchSn the value for FIP.FIP_CUTPAYDETL.BATCH_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBatchSn(String batchSn) {
        this.batchSn = batchSn == null ? null : batchSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BATCH_DETL_SN
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BATCH_DETL_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBatchDetlSn() {
        return batchDetlSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BATCH_DETL_SN
     *
     * @param batchDetlSn the value for FIP.FIP_CUTPAYDETL.BATCH_DETL_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBatchDetlSn(String batchDetlSn) {
        this.batchDetlSn = batchDetlSn == null ? null : batchDetlSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.TXPKG_SN
     *
     * @return the value of FIP.FIP_CUTPAYDETL.TXPKG_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getTxpkgSn() {
        return txpkgSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.TXPKG_SN
     *
     * @param txpkgSn the value for FIP.FIP_CUTPAYDETL.TXPKG_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setTxpkgSn(String txpkgSn) {
        this.txpkgSn = txpkgSn == null ? null : txpkgSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.TXPKG_DETL_SN
     *
     * @return the value of FIP.FIP_CUTPAYDETL.TXPKG_DETL_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getTxpkgDetlSn() {
        return txpkgDetlSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.TXPKG_DETL_SN
     *
     * @param txpkgDetlSn the value for FIP.FIP_CUTPAYDETL.TXPKG_DETL_SN
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setTxpkgDetlSn(String txpkgDetlSn) {
        this.txpkgDetlSn = txpkgDetlSn == null ? null : txpkgDetlSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.XFAPP_PKID
     *
     * @return the value of FIP.FIP_CUTPAYDETL.XFAPP_PKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getXfappPkid() {
        return xfappPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.XFAPP_PKID
     *
     * @param xfappPkid the value for FIP.FIP_CUTPAYDETL.XFAPP_PKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setXfappPkid(String xfappPkid) {
        this.xfappPkid = xfappPkid == null ? null : xfappPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.APPNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.APPNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getAppno() {
        return appno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.APPNO
     *
     * @param appno the value for FIP.FIP_CUTPAYDETL.APPNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setAppno(String appno) {
        this.appno = appno == null ? null : appno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.IOUNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.IOUNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getIouno() {
        return iouno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.IOUNO
     *
     * @param iouno the value for FIP.FIP_CUTPAYDETL.IOUNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setIouno(String iouno) {
        this.iouno = iouno == null ? null : iouno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.POANO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.POANO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getPoano() {
        return poano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.POANO
     *
     * @param poano the value for FIP.FIP_CUTPAYDETL.POANO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPoano(String poano) {
        this.poano = poano == null ? null : poano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.CONTRACTNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.CONTRACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getContractno() {
        return contractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.CONTRACTNO
     *
     * @param contractno the value for FIP.FIP_CUTPAYDETL.CONTRACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setContractno(String contractno) {
        this.contractno = contractno == null ? null : contractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.CLIENTNAME
     *
     * @return the value of FIP.FIP_CUTPAYDETL.CLIENTNAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.CLIENTNAME
     *
     * @param clientname the value for FIP.FIP_CUTPAYDETL.CLIENTNAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.CLIENTACT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.CLIENTACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getClientact() {
        return clientact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.CLIENTACT
     *
     * @param clientact the value for FIP.FIP_CUTPAYDETL.CLIENTACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setClientact(String clientact) {
        this.clientact = clientact == null ? null : clientact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PAYBACKAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PAYBACKAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getPaybackamt() {
        return paybackamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PAYBACKAMT
     *
     * @param paybackamt the value for FIP.FIP_CUTPAYDETL.PAYBACKAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPaybackamt(BigDecimal paybackamt) {
        this.paybackamt = paybackamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PAYBACKDATE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PAYBACKDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getPaybackdate() {
        return paybackdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PAYBACKDATE
     *
     * @param paybackdate the value for FIP.FIP_CUTPAYDETL.PAYBACKDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPaybackdate(String paybackdate) {
        this.paybackdate = paybackdate == null ? null : paybackdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.RECVACT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.RECVACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getRecvact() {
        return recvact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.RECVACT
     *
     * @param recvact the value for FIP.FIP_CUTPAYDETL.RECVACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRecvact(String recvact) {
        this.recvact = recvact == null ? null : recvact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.RECVBANKID
     *
     * @return the value of FIP.FIP_CUTPAYDETL.RECVBANKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getRecvbankid() {
        return recvbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.RECVBANKID
     *
     * @param recvbankid the value for FIP.FIP_CUTPAYDETL.RECVBANKID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRecvbankid(String recvbankid) {
        this.recvbankid = recvbankid == null ? null : recvbankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.RECVBANKNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.RECVBANKNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getRecvbankno() {
        return recvbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.RECVBANKNO
     *
     * @param recvbankno the value for FIP.FIP_CUTPAYDETL.RECVBANKNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRecvbankno(String recvbankno) {
        this.recvbankno = recvbankno == null ? null : recvbankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.STARTDATE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.STARTDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.STARTDATE
     *
     * @param startdate the value for FIP.FIP_CUTPAYDETL.STARTDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BILLSTATUS
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BILLSTATUS
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBillstatus() {
        return billstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BILLSTATUS
     *
     * @param billstatus the value for FIP.FIP_CUTPAYDETL.BILLSTATUS
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBillstatus(String billstatus) {
        this.billstatus = billstatus == null ? null : billstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PAIDUPAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PAIDUPAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getPaidupamt() {
        return paidupamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PAIDUPAMT
     *
     * @param paidupamt the value for FIP.FIP_CUTPAYDETL.PAIDUPAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPaidupamt(BigDecimal paidupamt) {
        this.paidupamt = paidupamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PAIDUPDATE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PAIDUPDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getPaidupdate() {
        return paidupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PAIDUPDATE
     *
     * @param paidupdate the value for FIP.FIP_CUTPAYDETL.PAIDUPDATE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPaidupdate(String paidupdate) {
        this.paidupdate = paidupdate == null ? null : paidupdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PRINCIPALAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PRINCIPALAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getPrincipalamt() {
        return principalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PRINCIPALAMT
     *
     * @param principalamt the value for FIP.FIP_CUTPAYDETL.PRINCIPALAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPrincipalamt(BigDecimal principalamt) {
        this.principalamt = principalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.INTERESTAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.INTERESTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getInterestamt() {
        return interestamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.INTERESTAMT
     *
     * @param interestamt the value for FIP.FIP_CUTPAYDETL.INTERESTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setInterestamt(BigDecimal interestamt) {
        this.interestamt = interestamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.PUNITIVEINTAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.PUNITIVEINTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getPunitiveintamt() {
        return punitiveintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.PUNITIVEINTAMT
     *
     * @param punitiveintamt the value for FIP.FIP_CUTPAYDETL.PUNITIVEINTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setPunitiveintamt(BigDecimal punitiveintamt) {
        this.punitiveintamt = punitiveintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BREAKAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BREAKAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getBreakamt() {
        return breakamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BREAKAMT
     *
     * @param breakamt the value for FIP.FIP_CUTPAYDETL.BREAKAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBreakamt(BigDecimal breakamt) {
        this.breakamt = breakamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.COMPOUNDINTAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.COMPOUNDINTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getCompoundintamt() {
        return compoundintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.COMPOUNDINTAMT
     *
     * @param compoundintamt the value for FIP.FIP_CUTPAYDETL.COMPOUNDINTAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setCompoundintamt(BigDecimal compoundintamt) {
        this.compoundintamt = compoundintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.RESERVEAMT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.RESERVEAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public BigDecimal getReserveamt() {
        return reserveamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.RESERVEAMT
     *
     * @param reserveamt the value for FIP.FIP_CUTPAYDETL.RESERVEAMT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setReserveamt(BigDecimal reserveamt) {
        this.reserveamt = reserveamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BILLTYPE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BILLTYPE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BILLTYPE
     *
     * @param billtype the value for FIP.FIP_CUTPAYDETL.BILLTYPE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBilltype(String billtype) {
        this.billtype = billtype == null ? null : billtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.CLIENTNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.CLIENTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getClientno() {
        return clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.CLIENTNO
     *
     * @param clientno the value for FIP.FIP_CUTPAYDETL.CLIENTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setClientno(String clientno) {
        this.clientno = clientno == null ? null : clientno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.CLIENTIDTYPE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.CLIENTIDTYPE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getClientidtype() {
        return clientidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.CLIENTIDTYPE
     *
     * @param clientidtype the value for FIP.FIP_CUTPAYDETL.CLIENTIDTYPE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setClientidtype(String clientidtype) {
        this.clientidtype = clientidtype == null ? null : clientidtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.CLIENTID
     *
     * @return the value of FIP.FIP_CUTPAYDETL.CLIENTID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.CLIENTID
     *
     * @param clientid the value for FIP.FIP_CUTPAYDETL.CLIENTID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiActopeningbank() {
        return biActopeningbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK
     *
     * @param biActopeningbank the value for FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiActopeningbank(String biActopeningbank) {
        this.biActopeningbank = biActopeningbank == null ? null : biActopeningbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_BANKACTNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_BANKACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiBankactno() {
        return biBankactno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_BANKACTNO
     *
     * @param biBankactno the value for FIP.FIP_CUTPAYDETL.BI_BANKACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiBankactno(String biBankactno) {
        this.biBankactno = biBankactno == null ? null : biBankactno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK_UD
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK_UD
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiActopeningbankUd() {
        return biActopeningbankUd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK_UD
     *
     * @param biActopeningbankUd the value for FIP.FIP_CUTPAYDETL.BI_ACTOPENINGBANK_UD
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiActopeningbankUd(String biActopeningbankUd) {
        this.biActopeningbankUd = biActopeningbankUd == null ? null : biActopeningbankUd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_BANKACTNAME
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_BANKACTNAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiBankactname() {
        return biBankactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_BANKACTNAME
     *
     * @param biBankactname the value for FIP.FIP_CUTPAYDETL.BI_BANKACTNAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiBankactname(String biBankactname) {
        this.biBankactname = biBankactname == null ? null : biBankactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_CUSTOMER_CODE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_CUSTOMER_CODE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiCustomerCode() {
        return biCustomerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_CUSTOMER_CODE
     *
     * @param biCustomerCode the value for FIP.FIP_CUTPAYDETL.BI_CUSTOMER_CODE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiCustomerCode(String biCustomerCode) {
        this.biCustomerCode = biCustomerCode == null ? null : biCustomerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_SIGN_ACCOUNT_NO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_SIGN_ACCOUNT_NO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiSignAccountNo() {
        return biSignAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_SIGN_ACCOUNT_NO
     *
     * @param biSignAccountNo the value for FIP.FIP_CUTPAYDETL.BI_SIGN_ACCOUNT_NO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiSignAccountNo(String biSignAccountNo) {
        this.biSignAccountNo = biSignAccountNo == null ? null : biSignAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_CHANNEL
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_CHANNEL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiChannel() {
        return biChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_CHANNEL
     *
     * @param biChannel the value for FIP.FIP_CUTPAYDETL.BI_CHANNEL
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiChannel(String biChannel) {
        this.biChannel = biChannel == null ? null : biChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_PROVINCE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_PROVINCE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiProvince() {
        return biProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_PROVINCE
     *
     * @param biProvince the value for FIP.FIP_CUTPAYDETL.BI_PROVINCE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiProvince(String biProvince) {
        this.biProvince = biProvince == null ? null : biProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.BI_CITY
     *
     * @return the value of FIP.FIP_CUTPAYDETL.BI_CITY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getBiCity() {
        return biCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.BI_CITY
     *
     * @param biCity the value for FIP.FIP_CUTPAYDETL.BI_CITY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setBiCity(String biCity) {
        this.biCity = biCity == null ? null : biCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.TX_RETCODE
     *
     * @return the value of FIP.FIP_CUTPAYDETL.TX_RETCODE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getTxRetcode() {
        return txRetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.TX_RETCODE
     *
     * @param txRetcode the value for FIP.FIP_CUTPAYDETL.TX_RETCODE
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setTxRetcode(String txRetcode) {
        this.txRetcode = txRetcode == null ? null : txRetcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.TX_RETMSG
     *
     * @return the value of FIP.FIP_CUTPAYDETL.TX_RETMSG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getTxRetmsg() {
        return txRetmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.TX_RETMSG
     *
     * @param txRetmsg the value for FIP.FIP_CUTPAYDETL.TX_RETMSG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setTxRetmsg(String txRetmsg) {
        this.txRetmsg = txRetmsg == null ? null : txRetmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.ORIGIN_BIZID
     *
     * @return the value of FIP.FIP_CUTPAYDETL.ORIGIN_BIZID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getOriginBizid() {
        return originBizid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.ORIGIN_BIZID
     *
     * @param originBizid the value for FIP.FIP_CUTPAYDETL.ORIGIN_BIZID
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setOriginBizid(String originBizid) {
        this.originBizid = originBizid == null ? null : originBizid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.SENDFLAG
     *
     * @return the value of FIP.FIP_CUTPAYDETL.SENDFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getSendflag() {
        return sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.SENDFLAG
     *
     * @param sendflag the value for FIP.FIP_CUTPAYDETL.SENDFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setSendflag(String sendflag) {
        this.sendflag = sendflag == null ? null : sendflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.ARCHIVEFLAG
     *
     * @return the value of FIP.FIP_CUTPAYDETL.ARCHIVEFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getArchiveflag() {
        return archiveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.ARCHIVEFLAG
     *
     * @param archiveflag the value for FIP.FIP_CUTPAYDETL.ARCHIVEFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setArchiveflag(String archiveflag) {
        this.archiveflag = archiveflag == null ? null : archiveflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.DELETEDFLAG
     *
     * @return the value of FIP.FIP_CUTPAYDETL.DELETEDFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.DELETEDFLAG
     *
     * @param deletedflag the value for FIP.FIP_CUTPAYDETL.DELETEDFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setDeletedflag(String deletedflag) {
        this.deletedflag = deletedflag == null ? null : deletedflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.RECVERSION
     *
     * @return the value of FIP.FIP_CUTPAYDETL.RECVERSION
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public Long getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.RECVERSION
     *
     * @param recversion the value for FIP.FIP_CUTPAYDETL.RECVERSION
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRecversion(Long recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.MERCHANT_NAME
     *
     * @return the value of FIP.FIP_CUTPAYDETL.MERCHANT_NAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.MERCHANT_NAME
     *
     * @param merchantName the value for FIP.FIP_CUTPAYDETL.MERCHANT_NAME
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.MERCHANT_ACTNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.MERCHANT_ACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getMerchantActno() {
        return merchantActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.MERCHANT_ACTNO
     *
     * @param merchantActno the value for FIP.FIP_CUTPAYDETL.MERCHANT_ACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setMerchantActno(String merchantActno) {
        this.merchantActno = merchantActno == null ? null : merchantActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.DATE_CMS_GET
     *
     * @return the value of FIP.FIP_CUTPAYDETL.DATE_CMS_GET
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public Date getDateCmsGet() {
        return dateCmsGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.DATE_CMS_GET
     *
     * @param dateCmsGet the value for FIP.FIP_CUTPAYDETL.DATE_CMS_GET
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setDateCmsGet(Date dateCmsGet) {
        this.dateCmsGet = dateCmsGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.DATE_BANK_CUTPAY
     *
     * @return the value of FIP.FIP_CUTPAYDETL.DATE_BANK_CUTPAY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public Date getDateBankCutpay() {
        return dateBankCutpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.DATE_BANK_CUTPAY
     *
     * @param dateBankCutpay the value for FIP.FIP_CUTPAYDETL.DATE_BANK_CUTPAY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setDateBankCutpay(Date dateBankCutpay) {
        this.dateBankCutpay = dateBankCutpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.DATE_SBS_ACT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.DATE_SBS_ACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public Date getDateSbsAct() {
        return dateSbsAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.DATE_SBS_ACT
     *
     * @param dateSbsAct the value for FIP.FIP_CUTPAYDETL.DATE_SBS_ACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setDateSbsAct(Date dateSbsAct) {
        this.dateSbsAct = dateSbsAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.DATE_CMS_PUT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.DATE_CMS_PUT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public Date getDateCmsPut() {
        return dateCmsPut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.DATE_CMS_PUT
     *
     * @param dateCmsPut the value for FIP.FIP_CUTPAYDETL.DATE_CMS_PUT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setDateCmsPut(Date dateCmsPut) {
        this.dateCmsPut = dateCmsPut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.USER_CMS_GET
     *
     * @return the value of FIP.FIP_CUTPAYDETL.USER_CMS_GET
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getUserCmsGet() {
        return userCmsGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.USER_CMS_GET
     *
     * @param userCmsGet the value for FIP.FIP_CUTPAYDETL.USER_CMS_GET
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setUserCmsGet(String userCmsGet) {
        this.userCmsGet = userCmsGet == null ? null : userCmsGet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.USER_BANK_CUTPAY
     *
     * @return the value of FIP.FIP_CUTPAYDETL.USER_BANK_CUTPAY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getUserBankCutpay() {
        return userBankCutpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.USER_BANK_CUTPAY
     *
     * @param userBankCutpay the value for FIP.FIP_CUTPAYDETL.USER_BANK_CUTPAY
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setUserBankCutpay(String userBankCutpay) {
        this.userBankCutpay = userBankCutpay == null ? null : userBankCutpay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.USER_SBS_ACT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.USER_SBS_ACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getUserSbsAct() {
        return userSbsAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.USER_SBS_ACT
     *
     * @param userSbsAct the value for FIP.FIP_CUTPAYDETL.USER_SBS_ACT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setUserSbsAct(String userSbsAct) {
        this.userSbsAct = userSbsAct == null ? null : userSbsAct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.USER_CMS_PUT
     *
     * @return the value of FIP.FIP_CUTPAYDETL.USER_CMS_PUT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getUserCmsPut() {
        return userCmsPut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.USER_CMS_PUT
     *
     * @param userCmsPut the value for FIP.FIP_CUTPAYDETL.USER_CMS_PUT
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setUserCmsPut(String userCmsPut) {
        this.userCmsPut = userCmsPut == null ? null : userCmsPut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.SBS_INTERBANK_ACTNO
     *
     * @return the value of FIP.FIP_CUTPAYDETL.SBS_INTERBANK_ACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getSbsInterbankActno() {
        return sbsInterbankActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.SBS_INTERBANK_ACTNO
     *
     * @param sbsInterbankActno the value for FIP.FIP_CUTPAYDETL.SBS_INTERBANK_ACTNO
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setSbsInterbankActno(String sbsInterbankActno) {
        this.sbsInterbankActno = sbsInterbankActno == null ? null : sbsInterbankActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.REMARK1
     *
     * @return the value of FIP.FIP_CUTPAYDETL.REMARK1
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.REMARK1
     *
     * @param remark1 the value for FIP.FIP_CUTPAYDETL.REMARK1
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.REMARK2
     *
     * @return the value of FIP.FIP_CUTPAYDETL.REMARK2
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.REMARK2
     *
     * @param remark2 the value for FIP.FIP_CUTPAYDETL.REMARK2
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.REMARK3
     *
     * @return the value of FIP.FIP_CUTPAYDETL.REMARK3
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.REMARK3
     *
     * @param remark3 the value for FIP.FIP_CUTPAYDETL.REMARK3
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.WRITEBACKFLAG
     *
     * @return the value of FIP.FIP_CUTPAYDETL.WRITEBACKFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getWritebackflag() {
        return writebackflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.WRITEBACKFLAG
     *
     * @param writebackflag the value for FIP.FIP_CUTPAYDETL.WRITEBACKFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setWritebackflag(String writebackflag) {
        this.writebackflag = writebackflag == null ? null : writebackflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_CUTPAYDETL.ACCOUNTFLAG
     *
     * @return the value of FIP.FIP_CUTPAYDETL.ACCOUNTFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public String getAccountflag() {
        return accountflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_CUTPAYDETL.ACCOUNTFLAG
     *
     * @param accountflag the value for FIP.FIP_CUTPAYDETL.ACCOUNTFLAG
     *
     * @mbggenerated Wed Jul 11 10:36:34 CST 2012
     */
    public void setAccountflag(String accountflag) {
        this.accountflag = accountflag == null ? null : accountflag.trim();
    }
}