package fip.repository.model;

public class FipPayoutbat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.PKID
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.REQ_SN
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String reqSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.TRX_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String trxCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.WSYS_ID
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String wsysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.TOTAL_ITEM
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String totalItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.TOTAL_SUM
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String totalSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.RET_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String retCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.ERR_MSG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String errMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.TRX_STEP
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String trxStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.REMARK
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.CREATE_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.UNIONPAY_TXN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String unionpayTxnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.QRYRTN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String qryrtnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.SBS_TXN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String sbsTxnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.UNIONPAY_RET_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String unionpayRetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.UNIONPAY_ERR_MSG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String unionpayErrMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.FIP_PAYOUTBAT.DELETE_FLAG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.PKID
     *
     * @return the value of FIP.FIP_PAYOUTBAT.PKID
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.PKID
     *
     * @param pkid the value for FIP.FIP_PAYOUTBAT.PKID
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.REQ_SN
     *
     * @return the value of FIP.FIP_PAYOUTBAT.REQ_SN
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getReqSn() {
        return reqSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.REQ_SN
     *
     * @param reqSn the value for FIP.FIP_PAYOUTBAT.REQ_SN
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setReqSn(String reqSn) {
        this.reqSn = reqSn == null ? null : reqSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.TRX_CODE
     *
     * @return the value of FIP.FIP_PAYOUTBAT.TRX_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getTrxCode() {
        return trxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.TRX_CODE
     *
     * @param trxCode the value for FIP.FIP_PAYOUTBAT.TRX_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setTrxCode(String trxCode) {
        this.trxCode = trxCode == null ? null : trxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.WSYS_ID
     *
     * @return the value of FIP.FIP_PAYOUTBAT.WSYS_ID
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getWsysId() {
        return wsysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.WSYS_ID
     *
     * @param wsysId the value for FIP.FIP_PAYOUTBAT.WSYS_ID
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setWsysId(String wsysId) {
        this.wsysId = wsysId == null ? null : wsysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.TOTAL_ITEM
     *
     * @return the value of FIP.FIP_PAYOUTBAT.TOTAL_ITEM
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getTotalItem() {
        return totalItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.TOTAL_ITEM
     *
     * @param totalItem the value for FIP.FIP_PAYOUTBAT.TOTAL_ITEM
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setTotalItem(String totalItem) {
        this.totalItem = totalItem == null ? null : totalItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.TOTAL_SUM
     *
     * @return the value of FIP.FIP_PAYOUTBAT.TOTAL_SUM
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getTotalSum() {
        return totalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.TOTAL_SUM
     *
     * @param totalSum the value for FIP.FIP_PAYOUTBAT.TOTAL_SUM
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setTotalSum(String totalSum) {
        this.totalSum = totalSum == null ? null : totalSum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.RET_CODE
     *
     * @return the value of FIP.FIP_PAYOUTBAT.RET_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getRetCode() {
        return retCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.RET_CODE
     *
     * @param retCode the value for FIP.FIP_PAYOUTBAT.RET_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setRetCode(String retCode) {
        this.retCode = retCode == null ? null : retCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.ERR_MSG
     *
     * @return the value of FIP.FIP_PAYOUTBAT.ERR_MSG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.ERR_MSG
     *
     * @param errMsg the value for FIP.FIP_PAYOUTBAT.ERR_MSG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg == null ? null : errMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.TRX_STEP
     *
     * @return the value of FIP.FIP_PAYOUTBAT.TRX_STEP
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getTrxStep() {
        return trxStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.TRX_STEP
     *
     * @param trxStep the value for FIP.FIP_PAYOUTBAT.TRX_STEP
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setTrxStep(String trxStep) {
        this.trxStep = trxStep == null ? null : trxStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.REMARK
     *
     * @return the value of FIP.FIP_PAYOUTBAT.REMARK
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.REMARK
     *
     * @param remark the value for FIP.FIP_PAYOUTBAT.REMARK
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.CREATE_TIME
     *
     * @return the value of FIP.FIP_PAYOUTBAT.CREATE_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.CREATE_TIME
     *
     * @param createTime the value for FIP.FIP_PAYOUTBAT.CREATE_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.UNIONPAY_TXN_TIME
     *
     * @return the value of FIP.FIP_PAYOUTBAT.UNIONPAY_TXN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getUnionpayTxnTime() {
        return unionpayTxnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.UNIONPAY_TXN_TIME
     *
     * @param unionpayTxnTime the value for FIP.FIP_PAYOUTBAT.UNIONPAY_TXN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setUnionpayTxnTime(String unionpayTxnTime) {
        this.unionpayTxnTime = unionpayTxnTime == null ? null : unionpayTxnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.QRYRTN_TIME
     *
     * @return the value of FIP.FIP_PAYOUTBAT.QRYRTN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getQryrtnTime() {
        return qryrtnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.QRYRTN_TIME
     *
     * @param qryrtnTime the value for FIP.FIP_PAYOUTBAT.QRYRTN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setQryrtnTime(String qryrtnTime) {
        this.qryrtnTime = qryrtnTime == null ? null : qryrtnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.SBS_TXN_TIME
     *
     * @return the value of FIP.FIP_PAYOUTBAT.SBS_TXN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getSbsTxnTime() {
        return sbsTxnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.SBS_TXN_TIME
     *
     * @param sbsTxnTime the value for FIP.FIP_PAYOUTBAT.SBS_TXN_TIME
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setSbsTxnTime(String sbsTxnTime) {
        this.sbsTxnTime = sbsTxnTime == null ? null : sbsTxnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.UNIONPAY_RET_CODE
     *
     * @return the value of FIP.FIP_PAYOUTBAT.UNIONPAY_RET_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getUnionpayRetCode() {
        return unionpayRetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.UNIONPAY_RET_CODE
     *
     * @param unionpayRetCode the value for FIP.FIP_PAYOUTBAT.UNIONPAY_RET_CODE
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setUnionpayRetCode(String unionpayRetCode) {
        this.unionpayRetCode = unionpayRetCode == null ? null : unionpayRetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.UNIONPAY_ERR_MSG
     *
     * @return the value of FIP.FIP_PAYOUTBAT.UNIONPAY_ERR_MSG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getUnionpayErrMsg() {
        return unionpayErrMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.UNIONPAY_ERR_MSG
     *
     * @param unionpayErrMsg the value for FIP.FIP_PAYOUTBAT.UNIONPAY_ERR_MSG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setUnionpayErrMsg(String unionpayErrMsg) {
        this.unionpayErrMsg = unionpayErrMsg == null ? null : unionpayErrMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.FIP_PAYOUTBAT.DELETE_FLAG
     *
     * @return the value of FIP.FIP_PAYOUTBAT.DELETE_FLAG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.FIP_PAYOUTBAT.DELETE_FLAG
     *
     * @param deleteFlag the value for FIP.FIP_PAYOUTBAT.DELETE_FLAG
     *
     * @mbggenerated Wed Apr 17 13:25:02 CST 2013
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}