package fip.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class Xfactcutpaydetl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.JOURNALNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String journalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CONTRACTNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String contractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.POANO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal poano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CLIENTNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String clientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CLIENTACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String clientact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal paybackamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date paybackdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String paybackact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKACTNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String paybackactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKBANKID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String paybackbankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKBANKNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String paybackbankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAYBACKBANKNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String paybackbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.RECVACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String recvact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.RECVBANKID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String recvbankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.RECVBANKNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String recvbankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.STARTDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.BILLSTATUS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String billstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAIDUPAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal paidupamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PAIDUPDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date paidupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.OPERATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.OPERATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date operatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CHECKERID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String checkerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CHECKDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CREATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CREATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CREATEFORM
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String createform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.UPDATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String updatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.UPDATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.UPDATEFORM
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String updateform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.PRINCIPALAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal principalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.SERVICECHARGEFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal servicechargefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.LATEFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal latefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.BREACHFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal breachfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.BILLTYPE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String billtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CUSTOMER_CODE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.SIGN_ACCOUNT_NO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String signAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CLIENTNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String clientno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CLIENTIDTYPE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String clientidtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.CLIENTID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.FAILUREREASON
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String failurereason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFACTCUTPAYDETL.TXJOURNALNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String txjournalno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.JOURNALNO
     *
     * @return the value of XFACTCUTPAYDETL.JOURNALNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getJournalno() {
        return journalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.JOURNALNO
     *
     * @param journalno the value for XFACTCUTPAYDETL.JOURNALNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setJournalno(String journalno) {
        this.journalno = journalno == null ? null : journalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CONTRACTNO
     *
     * @return the value of XFACTCUTPAYDETL.CONTRACTNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getContractno() {
        return contractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CONTRACTNO
     *
     * @param contractno the value for XFACTCUTPAYDETL.CONTRACTNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setContractno(String contractno) {
        this.contractno = contractno == null ? null : contractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.POANO
     *
     * @return the value of XFACTCUTPAYDETL.POANO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getPoano() {
        return poano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.POANO
     *
     * @param poano the value for XFACTCUTPAYDETL.POANO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPoano(BigDecimal poano) {
        this.poano = poano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CLIENTNAME
     *
     * @return the value of XFACTCUTPAYDETL.CLIENTNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CLIENTNAME
     *
     * @param clientname the value for XFACTCUTPAYDETL.CLIENTNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CLIENTACT
     *
     * @return the value of XFACTCUTPAYDETL.CLIENTACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getClientact() {
        return clientact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CLIENTACT
     *
     * @param clientact the value for XFACTCUTPAYDETL.CLIENTACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setClientact(String clientact) {
        this.clientact = clientact == null ? null : clientact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKAMT
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getPaybackamt() {
        return paybackamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKAMT
     *
     * @param paybackamt the value for XFACTCUTPAYDETL.PAYBACKAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackamt(BigDecimal paybackamt) {
        this.paybackamt = paybackamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKDATE
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getPaybackdate() {
        return paybackdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKDATE
     *
     * @param paybackdate the value for XFACTCUTPAYDETL.PAYBACKDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackdate(Date paybackdate) {
        this.paybackdate = paybackdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKACT
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getPaybackact() {
        return paybackact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKACT
     *
     * @param paybackact the value for XFACTCUTPAYDETL.PAYBACKACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackact(String paybackact) {
        this.paybackact = paybackact == null ? null : paybackact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKACTNAME
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKACTNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getPaybackactname() {
        return paybackactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKACTNAME
     *
     * @param paybackactname the value for XFACTCUTPAYDETL.PAYBACKACTNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackactname(String paybackactname) {
        this.paybackactname = paybackactname == null ? null : paybackactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKBANKID
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKBANKID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getPaybackbankid() {
        return paybackbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKBANKID
     *
     * @param paybackbankid the value for XFACTCUTPAYDETL.PAYBACKBANKID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackbankid(String paybackbankid) {
        this.paybackbankid = paybackbankid == null ? null : paybackbankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKBANKNO
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKBANKNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getPaybackbankno() {
        return paybackbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKBANKNO
     *
     * @param paybackbankno the value for XFACTCUTPAYDETL.PAYBACKBANKNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackbankno(String paybackbankno) {
        this.paybackbankno = paybackbankno == null ? null : paybackbankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAYBACKBANKNAME
     *
     * @return the value of XFACTCUTPAYDETL.PAYBACKBANKNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getPaybackbankname() {
        return paybackbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAYBACKBANKNAME
     *
     * @param paybackbankname the value for XFACTCUTPAYDETL.PAYBACKBANKNAME
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaybackbankname(String paybackbankname) {
        this.paybackbankname = paybackbankname == null ? null : paybackbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.RECVACT
     *
     * @return the value of XFACTCUTPAYDETL.RECVACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getRecvact() {
        return recvact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.RECVACT
     *
     * @param recvact the value for XFACTCUTPAYDETL.RECVACT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setRecvact(String recvact) {
        this.recvact = recvact == null ? null : recvact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.RECVBANKID
     *
     * @return the value of XFACTCUTPAYDETL.RECVBANKID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getRecvbankid() {
        return recvbankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.RECVBANKID
     *
     * @param recvbankid the value for XFACTCUTPAYDETL.RECVBANKID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setRecvbankid(String recvbankid) {
        this.recvbankid = recvbankid == null ? null : recvbankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.RECVBANKNO
     *
     * @return the value of XFACTCUTPAYDETL.RECVBANKNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getRecvbankno() {
        return recvbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.RECVBANKNO
     *
     * @param recvbankno the value for XFACTCUTPAYDETL.RECVBANKNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setRecvbankno(String recvbankno) {
        this.recvbankno = recvbankno == null ? null : recvbankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.STARTDATE
     *
     * @return the value of XFACTCUTPAYDETL.STARTDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.STARTDATE
     *
     * @param startdate the value for XFACTCUTPAYDETL.STARTDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.BILLSTATUS
     *
     * @return the value of XFACTCUTPAYDETL.BILLSTATUS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getBillstatus() {
        return billstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.BILLSTATUS
     *
     * @param billstatus the value for XFACTCUTPAYDETL.BILLSTATUS
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setBillstatus(String billstatus) {
        this.billstatus = billstatus == null ? null : billstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAIDUPAMT
     *
     * @return the value of XFACTCUTPAYDETL.PAIDUPAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getPaidupamt() {
        return paidupamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAIDUPAMT
     *
     * @param paidupamt the value for XFACTCUTPAYDETL.PAIDUPAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaidupamt(BigDecimal paidupamt) {
        this.paidupamt = paidupamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PAIDUPDATE
     *
     * @return the value of XFACTCUTPAYDETL.PAIDUPDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getPaidupdate() {
        return paidupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PAIDUPDATE
     *
     * @param paidupdate the value for XFACTCUTPAYDETL.PAIDUPDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPaidupdate(Date paidupdate) {
        this.paidupdate = paidupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.OPERATORID
     *
     * @return the value of XFACTCUTPAYDETL.OPERATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.OPERATORID
     *
     * @param operatorid the value for XFACTCUTPAYDETL.OPERATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid == null ? null : operatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.OPERATEDATE
     *
     * @return the value of XFACTCUTPAYDETL.OPERATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.OPERATEDATE
     *
     * @param operatedate the value for XFACTCUTPAYDETL.OPERATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CHECKERID
     *
     * @return the value of XFACTCUTPAYDETL.CHECKERID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getCheckerid() {
        return checkerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CHECKERID
     *
     * @param checkerid the value for XFACTCUTPAYDETL.CHECKERID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid == null ? null : checkerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CHECKDATE
     *
     * @return the value of XFACTCUTPAYDETL.CHECKDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CHECKDATE
     *
     * @param checkdate the value for XFACTCUTPAYDETL.CHECKDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCheckdate(Date checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CREATORID
     *
     * @return the value of XFACTCUTPAYDETL.CREATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CREATORID
     *
     * @param creatorid the value for XFACTCUTPAYDETL.CREATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CREATEDATE
     *
     * @return the value of XFACTCUTPAYDETL.CREATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CREATEDATE
     *
     * @param createdate the value for XFACTCUTPAYDETL.CREATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CREATEFORM
     *
     * @return the value of XFACTCUTPAYDETL.CREATEFORM
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getCreateform() {
        return createform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CREATEFORM
     *
     * @param createform the value for XFACTCUTPAYDETL.CREATEFORM
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCreateform(String createform) {
        this.createform = createform == null ? null : createform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.UPDATORID
     *
     * @return the value of XFACTCUTPAYDETL.UPDATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getUpdatorid() {
        return updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.UPDATORID
     *
     * @param updatorid the value for XFACTCUTPAYDETL.UPDATORID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setUpdatorid(String updatorid) {
        this.updatorid = updatorid == null ? null : updatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.UPDATEDATE
     *
     * @return the value of XFACTCUTPAYDETL.UPDATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.UPDATEDATE
     *
     * @param updatedate the value for XFACTCUTPAYDETL.UPDATEDATE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.UPDATEFORM
     *
     * @return the value of XFACTCUTPAYDETL.UPDATEFORM
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getUpdateform() {
        return updateform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.UPDATEFORM
     *
     * @param updateform the value for XFACTCUTPAYDETL.UPDATEFORM
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setUpdateform(String updateform) {
        this.updateform = updateform == null ? null : updateform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.PRINCIPALAMT
     *
     * @return the value of XFACTCUTPAYDETL.PRINCIPALAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getPrincipalamt() {
        return principalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.PRINCIPALAMT
     *
     * @param principalamt the value for XFACTCUTPAYDETL.PRINCIPALAMT
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setPrincipalamt(BigDecimal principalamt) {
        this.principalamt = principalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.SERVICECHARGEFEE
     *
     * @return the value of XFACTCUTPAYDETL.SERVICECHARGEFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getServicechargefee() {
        return servicechargefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.SERVICECHARGEFEE
     *
     * @param servicechargefee the value for XFACTCUTPAYDETL.SERVICECHARGEFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setServicechargefee(BigDecimal servicechargefee) {
        this.servicechargefee = servicechargefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.LATEFEE
     *
     * @return the value of XFACTCUTPAYDETL.LATEFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getLatefee() {
        return latefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.LATEFEE
     *
     * @param latefee the value for XFACTCUTPAYDETL.LATEFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setLatefee(BigDecimal latefee) {
        this.latefee = latefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.BREACHFEE
     *
     * @return the value of XFACTCUTPAYDETL.BREACHFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getBreachfee() {
        return breachfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.BREACHFEE
     *
     * @param breachfee the value for XFACTCUTPAYDETL.BREACHFEE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setBreachfee(BigDecimal breachfee) {
        this.breachfee = breachfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.BILLTYPE
     *
     * @return the value of XFACTCUTPAYDETL.BILLTYPE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.BILLTYPE
     *
     * @param billtype the value for XFACTCUTPAYDETL.BILLTYPE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setBilltype(String billtype) {
        this.billtype = billtype == null ? null : billtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CUSTOMER_CODE
     *
     * @return the value of XFACTCUTPAYDETL.CUSTOMER_CODE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CUSTOMER_CODE
     *
     * @param customerCode the value for XFACTCUTPAYDETL.CUSTOMER_CODE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.SIGN_ACCOUNT_NO
     *
     * @return the value of XFACTCUTPAYDETL.SIGN_ACCOUNT_NO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getSignAccountNo() {
        return signAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.SIGN_ACCOUNT_NO
     *
     * @param signAccountNo the value for XFACTCUTPAYDETL.SIGN_ACCOUNT_NO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setSignAccountNo(String signAccountNo) {
        this.signAccountNo = signAccountNo == null ? null : signAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CLIENTNO
     *
     * @return the value of XFACTCUTPAYDETL.CLIENTNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getClientno() {
        return clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CLIENTNO
     *
     * @param clientno the value for XFACTCUTPAYDETL.CLIENTNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setClientno(String clientno) {
        this.clientno = clientno == null ? null : clientno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CLIENTIDTYPE
     *
     * @return the value of XFACTCUTPAYDETL.CLIENTIDTYPE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getClientidtype() {
        return clientidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CLIENTIDTYPE
     *
     * @param clientidtype the value for XFACTCUTPAYDETL.CLIENTIDTYPE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setClientidtype(String clientidtype) {
        this.clientidtype = clientidtype == null ? null : clientidtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.CLIENTID
     *
     * @return the value of XFACTCUTPAYDETL.CLIENTID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.CLIENTID
     *
     * @param clientid the value for XFACTCUTPAYDETL.CLIENTID
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.FAILUREREASON
     *
     * @return the value of XFACTCUTPAYDETL.FAILUREREASON
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getFailurereason() {
        return failurereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.FAILUREREASON
     *
     * @param failurereason the value for XFACTCUTPAYDETL.FAILUREREASON
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setFailurereason(String failurereason) {
        this.failurereason = failurereason == null ? null : failurereason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFACTCUTPAYDETL.TXJOURNALNO
     *
     * @return the value of XFACTCUTPAYDETL.TXJOURNALNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getTxjournalno() {
        return txjournalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFACTCUTPAYDETL.TXJOURNALNO
     *
     * @param txjournalno the value for XFACTCUTPAYDETL.TXJOURNALNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setTxjournalno(String txjournalno) {
        this.txjournalno = txjournalno == null ? null : txjournalno.trim();
    }
}