package fip.repository.model;

import java.math.BigDecimal;

public class Xfappcommbatch extends XfappcommbatchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMMBATCH.COMMNMTYPE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String commnmtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMMBATCH.NUM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMMBATCH.AMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMMBATCH.RECEIVEAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal receiveamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMMBATCH.RECVERSION
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal recversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMMBATCH.COMMNMTYPE
     *
     * @return the value of FIP.XFAPPCOMMBATCH.COMMNMTYPE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getCommnmtype() {
        return commnmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMMBATCH.COMMNMTYPE
     *
     * @param commnmtype the value for FIP.XFAPPCOMMBATCH.COMMNMTYPE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setCommnmtype(String commnmtype) {
        this.commnmtype = commnmtype == null ? null : commnmtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMMBATCH.NUM
     *
     * @return the value of FIP.XFAPPCOMMBATCH.NUM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMMBATCH.NUM
     *
     * @param num the value for FIP.XFAPPCOMMBATCH.NUM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMMBATCH.AMT
     *
     * @return the value of FIP.XFAPPCOMMBATCH.AMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMMBATCH.AMT
     *
     * @param amt the value for FIP.XFAPPCOMMBATCH.AMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMMBATCH.RECEIVEAMT
     *
     * @return the value of FIP.XFAPPCOMMBATCH.RECEIVEAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getReceiveamt() {
        return receiveamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMMBATCH.RECEIVEAMT
     *
     * @param receiveamt the value for FIP.XFAPPCOMMBATCH.RECEIVEAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setReceiveamt(BigDecimal receiveamt) {
        this.receiveamt = receiveamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMMBATCH.RECVERSION
     *
     * @return the value of FIP.XFAPPCOMMBATCH.RECVERSION
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMMBATCH.RECVERSION
     *
     * @param recversion the value for FIP.XFAPPCOMMBATCH.RECVERSION
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setRecversion(BigDecimal recversion) {
        this.recversion = recversion;
    }
}