package fip.repository.model;

import java.util.Date;

public class Xfapprepayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.APPNO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String appno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.ACTOPENINGBANK
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String actopeningbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.BANKACTNO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String bankactno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.ACTOPENINGBANK_UD
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String actopeningbankUd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.BANKACTNAME
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String bankactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.CUSTOMER_CODE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.SIGN_ACCOUNT_NO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String signAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.CHANNEL
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.RECVERSION
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private Long recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.OPERID
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.OPERDATE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private Date operdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.PROVINCE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPREPAYMENT.CITY
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.APPNO
     *
     * @return the value of FIP.XFAPPREPAYMENT.APPNO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getAppno() {
        return appno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.APPNO
     *
     * @param appno the value for FIP.XFAPPREPAYMENT.APPNO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setAppno(String appno) {
        this.appno = appno == null ? null : appno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.ACTOPENINGBANK
     *
     * @return the value of FIP.XFAPPREPAYMENT.ACTOPENINGBANK
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getActopeningbank() {
        return actopeningbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.ACTOPENINGBANK
     *
     * @param actopeningbank the value for FIP.XFAPPREPAYMENT.ACTOPENINGBANK
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setActopeningbank(String actopeningbank) {
        this.actopeningbank = actopeningbank == null ? null : actopeningbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.BANKACTNO
     *
     * @return the value of FIP.XFAPPREPAYMENT.BANKACTNO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getBankactno() {
        return bankactno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.BANKACTNO
     *
     * @param bankactno the value for FIP.XFAPPREPAYMENT.BANKACTNO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setBankactno(String bankactno) {
        this.bankactno = bankactno == null ? null : bankactno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.ACTOPENINGBANK_UD
     *
     * @return the value of FIP.XFAPPREPAYMENT.ACTOPENINGBANK_UD
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getActopeningbankUd() {
        return actopeningbankUd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.ACTOPENINGBANK_UD
     *
     * @param actopeningbankUd the value for FIP.XFAPPREPAYMENT.ACTOPENINGBANK_UD
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setActopeningbankUd(String actopeningbankUd) {
        this.actopeningbankUd = actopeningbankUd == null ? null : actopeningbankUd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.BANKACTNAME
     *
     * @return the value of FIP.XFAPPREPAYMENT.BANKACTNAME
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getBankactname() {
        return bankactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.BANKACTNAME
     *
     * @param bankactname the value for FIP.XFAPPREPAYMENT.BANKACTNAME
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setBankactname(String bankactname) {
        this.bankactname = bankactname == null ? null : bankactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.CUSTOMER_CODE
     *
     * @return the value of FIP.XFAPPREPAYMENT.CUSTOMER_CODE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.CUSTOMER_CODE
     *
     * @param customerCode the value for FIP.XFAPPREPAYMENT.CUSTOMER_CODE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.SIGN_ACCOUNT_NO
     *
     * @return the value of FIP.XFAPPREPAYMENT.SIGN_ACCOUNT_NO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getSignAccountNo() {
        return signAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.SIGN_ACCOUNT_NO
     *
     * @param signAccountNo the value for FIP.XFAPPREPAYMENT.SIGN_ACCOUNT_NO
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setSignAccountNo(String signAccountNo) {
        this.signAccountNo = signAccountNo == null ? null : signAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.CHANNEL
     *
     * @return the value of FIP.XFAPPREPAYMENT.CHANNEL
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.CHANNEL
     *
     * @param channel the value for FIP.XFAPPREPAYMENT.CHANNEL
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.RECVERSION
     *
     * @return the value of FIP.XFAPPREPAYMENT.RECVERSION
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public Long getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.RECVERSION
     *
     * @param recversion the value for FIP.XFAPPREPAYMENT.RECVERSION
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setRecversion(Long recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.OPERID
     *
     * @return the value of FIP.XFAPPREPAYMENT.OPERID
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.OPERID
     *
     * @param operid the value for FIP.XFAPPREPAYMENT.OPERID
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.OPERDATE
     *
     * @return the value of FIP.XFAPPREPAYMENT.OPERDATE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public Date getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.OPERDATE
     *
     * @param operdate the value for FIP.XFAPPREPAYMENT.OPERDATE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setOperdate(Date operdate) {
        this.operdate = operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.PROVINCE
     *
     * @return the value of FIP.XFAPPREPAYMENT.PROVINCE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.PROVINCE
     *
     * @param province the value for FIP.XFAPPREPAYMENT.PROVINCE
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPREPAYMENT.CITY
     *
     * @return the value of FIP.XFAPPREPAYMENT.CITY
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPREPAYMENT.CITY
     *
     * @param city the value for FIP.XFAPPREPAYMENT.CITY
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}