package fip.repository.model;

import java.math.BigDecimal;

public class Xfappcomm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.APPNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String appno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.CHANNEL
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.COMMNAME
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String commname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.COMMTYPE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String commtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.ADDR
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.NUM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.AMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.RECEIVEAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal receiveamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.APPAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal appamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.DIVID
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String divid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.COMMISSIONRATE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private BigDecimal commissionrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.CMLOANACTNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String cmloanactno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.XFAPPCOMM.DBDEPOACTNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    private String dbdepoactno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.APPNO
     *
     * @return the value of FIP.XFAPPCOMM.APPNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getAppno() {
        return appno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.APPNO
     *
     * @param appno the value for FIP.XFAPPCOMM.APPNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setAppno(String appno) {
        this.appno = appno == null ? null : appno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.CHANNEL
     *
     * @return the value of FIP.XFAPPCOMM.CHANNEL
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.CHANNEL
     *
     * @param channel the value for FIP.XFAPPCOMM.CHANNEL
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.COMMNAME
     *
     * @return the value of FIP.XFAPPCOMM.COMMNAME
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getCommname() {
        return commname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.COMMNAME
     *
     * @param commname the value for FIP.XFAPPCOMM.COMMNAME
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setCommname(String commname) {
        this.commname = commname == null ? null : commname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.COMMTYPE
     *
     * @return the value of FIP.XFAPPCOMM.COMMTYPE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getCommtype() {
        return commtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.COMMTYPE
     *
     * @param commtype the value for FIP.XFAPPCOMM.COMMTYPE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setCommtype(String commtype) {
        this.commtype = commtype == null ? null : commtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.ADDR
     *
     * @return the value of FIP.XFAPPCOMM.ADDR
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.ADDR
     *
     * @param addr the value for FIP.XFAPPCOMM.ADDR
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.NUM
     *
     * @return the value of FIP.XFAPPCOMM.NUM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.NUM
     *
     * @param num the value for FIP.XFAPPCOMM.NUM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.AMT
     *
     * @return the value of FIP.XFAPPCOMM.AMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.AMT
     *
     * @param amt the value for FIP.XFAPPCOMM.AMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.RECEIVEAMT
     *
     * @return the value of FIP.XFAPPCOMM.RECEIVEAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getReceiveamt() {
        return receiveamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.RECEIVEAMT
     *
     * @param receiveamt the value for FIP.XFAPPCOMM.RECEIVEAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setReceiveamt(BigDecimal receiveamt) {
        this.receiveamt = receiveamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.APPAMT
     *
     * @return the value of FIP.XFAPPCOMM.APPAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getAppamt() {
        return appamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.APPAMT
     *
     * @param appamt the value for FIP.XFAPPCOMM.APPAMT
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setAppamt(BigDecimal appamt) {
        this.appamt = appamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.DIVID
     *
     * @return the value of FIP.XFAPPCOMM.DIVID
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getDivid() {
        return divid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.DIVID
     *
     * @param divid the value for FIP.XFAPPCOMM.DIVID
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setDivid(String divid) {
        this.divid = divid == null ? null : divid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.COMMISSIONRATE
     *
     * @return the value of FIP.XFAPPCOMM.COMMISSIONRATE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public BigDecimal getCommissionrate() {
        return commissionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.COMMISSIONRATE
     *
     * @param commissionrate the value for FIP.XFAPPCOMM.COMMISSIONRATE
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setCommissionrate(BigDecimal commissionrate) {
        this.commissionrate = commissionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.CMLOANACTNO
     *
     * @return the value of FIP.XFAPPCOMM.CMLOANACTNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getCmloanactno() {
        return cmloanactno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.CMLOANACTNO
     *
     * @param cmloanactno the value for FIP.XFAPPCOMM.CMLOANACTNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setCmloanactno(String cmloanactno) {
        this.cmloanactno = cmloanactno == null ? null : cmloanactno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.XFAPPCOMM.DBDEPOACTNO
     *
     * @return the value of FIP.XFAPPCOMM.DBDEPOACTNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getDbdepoactno() {
        return dbdepoactno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.XFAPPCOMM.DBDEPOACTNO
     *
     * @param dbdepoactno the value for FIP.XFAPPCOMM.DBDEPOACTNO
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setDbdepoactno(String dbdepoactno) {
        this.dbdepoactno = dbdepoactno == null ? null : dbdepoactno.trim();
    }
}