package fip.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XfapprepaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public XfapprepaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppnoIsNull() {
            addCriterion("APPNO is null");
            return (Criteria) this;
        }

        public Criteria andAppnoIsNotNull() {
            addCriterion("APPNO is not null");
            return (Criteria) this;
        }

        public Criteria andAppnoEqualTo(String value) {
            addCriterion("APPNO =", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotEqualTo(String value) {
            addCriterion("APPNO <>", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoGreaterThan(String value) {
            addCriterion("APPNO >", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoGreaterThanOrEqualTo(String value) {
            addCriterion("APPNO >=", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoLessThan(String value) {
            addCriterion("APPNO <", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoLessThanOrEqualTo(String value) {
            addCriterion("APPNO <=", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoLike(String value) {
            addCriterion("APPNO like", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotLike(String value) {
            addCriterion("APPNO not like", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoIn(List<String> values) {
            addCriterion("APPNO in", values, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotIn(List<String> values) {
            addCriterion("APPNO not in", values, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoBetween(String value1, String value2) {
            addCriterion("APPNO between", value1, value2, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotBetween(String value1, String value2) {
            addCriterion("APPNO not between", value1, value2, "appno");
            return (Criteria) this;
        }

        public Criteria andActopeningbankIsNull() {
            addCriterion("ACTOPENINGBANK is null");
            return (Criteria) this;
        }

        public Criteria andActopeningbankIsNotNull() {
            addCriterion("ACTOPENINGBANK is not null");
            return (Criteria) this;
        }

        public Criteria andActopeningbankEqualTo(String value) {
            addCriterion("ACTOPENINGBANK =", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankNotEqualTo(String value) {
            addCriterion("ACTOPENINGBANK <>", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankGreaterThan(String value) {
            addCriterion("ACTOPENINGBANK >", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankGreaterThanOrEqualTo(String value) {
            addCriterion("ACTOPENINGBANK >=", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankLessThan(String value) {
            addCriterion("ACTOPENINGBANK <", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankLessThanOrEqualTo(String value) {
            addCriterion("ACTOPENINGBANK <=", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankLike(String value) {
            addCriterion("ACTOPENINGBANK like", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankNotLike(String value) {
            addCriterion("ACTOPENINGBANK not like", value, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankIn(List<String> values) {
            addCriterion("ACTOPENINGBANK in", values, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankNotIn(List<String> values) {
            addCriterion("ACTOPENINGBANK not in", values, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankBetween(String value1, String value2) {
            addCriterion("ACTOPENINGBANK between", value1, value2, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andActopeningbankNotBetween(String value1, String value2) {
            addCriterion("ACTOPENINGBANK not between", value1, value2, "actopeningbank");
            return (Criteria) this;
        }

        public Criteria andBankactnoIsNull() {
            addCriterion("BANKACTNO is null");
            return (Criteria) this;
        }

        public Criteria andBankactnoIsNotNull() {
            addCriterion("BANKACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andBankactnoEqualTo(String value) {
            addCriterion("BANKACTNO =", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoNotEqualTo(String value) {
            addCriterion("BANKACTNO <>", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoGreaterThan(String value) {
            addCriterion("BANKACTNO >", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoGreaterThanOrEqualTo(String value) {
            addCriterion("BANKACTNO >=", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoLessThan(String value) {
            addCriterion("BANKACTNO <", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoLessThanOrEqualTo(String value) {
            addCriterion("BANKACTNO <=", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoLike(String value) {
            addCriterion("BANKACTNO like", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoNotLike(String value) {
            addCriterion("BANKACTNO not like", value, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoIn(List<String> values) {
            addCriterion("BANKACTNO in", values, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoNotIn(List<String> values) {
            addCriterion("BANKACTNO not in", values, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoBetween(String value1, String value2) {
            addCriterion("BANKACTNO between", value1, value2, "bankactno");
            return (Criteria) this;
        }

        public Criteria andBankactnoNotBetween(String value1, String value2) {
            addCriterion("BANKACTNO not between", value1, value2, "bankactno");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdIsNull() {
            addCriterion("ACTOPENINGBANK_UD is null");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdIsNotNull() {
            addCriterion("ACTOPENINGBANK_UD is not null");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdEqualTo(String value) {
            addCriterion("ACTOPENINGBANK_UD =", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdNotEqualTo(String value) {
            addCriterion("ACTOPENINGBANK_UD <>", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdGreaterThan(String value) {
            addCriterion("ACTOPENINGBANK_UD >", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdGreaterThanOrEqualTo(String value) {
            addCriterion("ACTOPENINGBANK_UD >=", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdLessThan(String value) {
            addCriterion("ACTOPENINGBANK_UD <", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdLessThanOrEqualTo(String value) {
            addCriterion("ACTOPENINGBANK_UD <=", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdLike(String value) {
            addCriterion("ACTOPENINGBANK_UD like", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdNotLike(String value) {
            addCriterion("ACTOPENINGBANK_UD not like", value, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdIn(List<String> values) {
            addCriterion("ACTOPENINGBANK_UD in", values, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdNotIn(List<String> values) {
            addCriterion("ACTOPENINGBANK_UD not in", values, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdBetween(String value1, String value2) {
            addCriterion("ACTOPENINGBANK_UD between", value1, value2, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andActopeningbankUdNotBetween(String value1, String value2) {
            addCriterion("ACTOPENINGBANK_UD not between", value1, value2, "actopeningbankUd");
            return (Criteria) this;
        }

        public Criteria andBankactnameIsNull() {
            addCriterion("BANKACTNAME is null");
            return (Criteria) this;
        }

        public Criteria andBankactnameIsNotNull() {
            addCriterion("BANKACTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankactnameEqualTo(String value) {
            addCriterion("BANKACTNAME =", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameNotEqualTo(String value) {
            addCriterion("BANKACTNAME <>", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameGreaterThan(String value) {
            addCriterion("BANKACTNAME >", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameGreaterThanOrEqualTo(String value) {
            addCriterion("BANKACTNAME >=", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameLessThan(String value) {
            addCriterion("BANKACTNAME <", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameLessThanOrEqualTo(String value) {
            addCriterion("BANKACTNAME <=", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameLike(String value) {
            addCriterion("BANKACTNAME like", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameNotLike(String value) {
            addCriterion("BANKACTNAME not like", value, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameIn(List<String> values) {
            addCriterion("BANKACTNAME in", values, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameNotIn(List<String> values) {
            addCriterion("BANKACTNAME not in", values, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameBetween(String value1, String value2) {
            addCriterion("BANKACTNAME between", value1, value2, "bankactname");
            return (Criteria) this;
        }

        public Criteria andBankactnameNotBetween(String value1, String value2) {
            addCriterion("BANKACTNAME not between", value1, value2, "bankactname");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeIsNull() {
            addCriterion("CUSTOMER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeIsNotNull() {
            addCriterion("CUSTOMER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeEqualTo(String value) {
            addCriterion("CUSTOMER_CODE =", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeNotEqualTo(String value) {
            addCriterion("CUSTOMER_CODE <>", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeGreaterThan(String value) {
            addCriterion("CUSTOMER_CODE >", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_CODE >=", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeLessThan(String value) {
            addCriterion("CUSTOMER_CODE <", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_CODE <=", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeLike(String value) {
            addCriterion("CUSTOMER_CODE like", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeNotLike(String value) {
            addCriterion("CUSTOMER_CODE not like", value, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeIn(List<String> values) {
            addCriterion("CUSTOMER_CODE in", values, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeNotIn(List<String> values) {
            addCriterion("CUSTOMER_CODE not in", values, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeBetween(String value1, String value2) {
            addCriterion("CUSTOMER_CODE between", value1, value2, "customerCode");
            return (Criteria) this;
        }

        public Criteria andCustomerCodeNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER_CODE not between", value1, value2, "customerCode");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoIsNull() {
            addCriterion("SIGN_ACCOUNT_NO is null");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoIsNotNull() {
            addCriterion("SIGN_ACCOUNT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoEqualTo(String value) {
            addCriterion("SIGN_ACCOUNT_NO =", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoNotEqualTo(String value) {
            addCriterion("SIGN_ACCOUNT_NO <>", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoGreaterThan(String value) {
            addCriterion("SIGN_ACCOUNT_NO >", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN_ACCOUNT_NO >=", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoLessThan(String value) {
            addCriterion("SIGN_ACCOUNT_NO <", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoLessThanOrEqualTo(String value) {
            addCriterion("SIGN_ACCOUNT_NO <=", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoLike(String value) {
            addCriterion("SIGN_ACCOUNT_NO like", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoNotLike(String value) {
            addCriterion("SIGN_ACCOUNT_NO not like", value, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoIn(List<String> values) {
            addCriterion("SIGN_ACCOUNT_NO in", values, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoNotIn(List<String> values) {
            addCriterion("SIGN_ACCOUNT_NO not in", values, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoBetween(String value1, String value2) {
            addCriterion("SIGN_ACCOUNT_NO between", value1, value2, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andSignAccountNoNotBetween(String value1, String value2) {
            addCriterion("SIGN_ACCOUNT_NO not between", value1, value2, "signAccountNo");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("CHANNEL =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("CHANNEL <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("CHANNEL >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("CHANNEL <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("CHANNEL like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("CHANNEL not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("CHANNEL in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("CHANNEL not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("CHANNEL between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("CHANNEL not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Long value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Long value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Long value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Long value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Long value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Long value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Long> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Long> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Long value1, Long value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Long value1, Long value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(Date value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(Date value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(Date value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(Date value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(Date value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<Date> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<Date> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(Date value1, Date value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(Date value1, Date value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 19 17:37:21 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIP.XFAPPREPAYMENT
     *
     * @mbggenerated Fri Aug 19 17:37:21 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}