package fip.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class XfappcommExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public XfappcommExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppnoIsNull() {
            addCriterion("APPNO is null");
            return (Criteria) this;
        }

        public Criteria andAppnoIsNotNull() {
            addCriterion("APPNO is not null");
            return (Criteria) this;
        }

        public Criteria andAppnoEqualTo(String value) {
            addCriterion("APPNO =", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotEqualTo(String value) {
            addCriterion("APPNO <>", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoGreaterThan(String value) {
            addCriterion("APPNO >", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoGreaterThanOrEqualTo(String value) {
            addCriterion("APPNO >=", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoLessThan(String value) {
            addCriterion("APPNO <", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoLessThanOrEqualTo(String value) {
            addCriterion("APPNO <=", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoLike(String value) {
            addCriterion("APPNO like", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotLike(String value) {
            addCriterion("APPNO not like", value, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoIn(List<String> values) {
            addCriterion("APPNO in", values, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotIn(List<String> values) {
            addCriterion("APPNO not in", values, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoBetween(String value1, String value2) {
            addCriterion("APPNO between", value1, value2, "appno");
            return (Criteria) this;
        }

        public Criteria andAppnoNotBetween(String value1, String value2) {
            addCriterion("APPNO not between", value1, value2, "appno");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("CHANNEL =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("CHANNEL <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("CHANNEL >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("CHANNEL <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("CHANNEL like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("CHANNEL not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("CHANNEL in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("CHANNEL not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("CHANNEL between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("CHANNEL not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andCommnameIsNull() {
            addCriterion("COMMNAME is null");
            return (Criteria) this;
        }

        public Criteria andCommnameIsNotNull() {
            addCriterion("COMMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCommnameEqualTo(String value) {
            addCriterion("COMMNAME =", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameNotEqualTo(String value) {
            addCriterion("COMMNAME <>", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameGreaterThan(String value) {
            addCriterion("COMMNAME >", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameGreaterThanOrEqualTo(String value) {
            addCriterion("COMMNAME >=", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameLessThan(String value) {
            addCriterion("COMMNAME <", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameLessThanOrEqualTo(String value) {
            addCriterion("COMMNAME <=", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameLike(String value) {
            addCriterion("COMMNAME like", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameNotLike(String value) {
            addCriterion("COMMNAME not like", value, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameIn(List<String> values) {
            addCriterion("COMMNAME in", values, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameNotIn(List<String> values) {
            addCriterion("COMMNAME not in", values, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameBetween(String value1, String value2) {
            addCriterion("COMMNAME between", value1, value2, "commname");
            return (Criteria) this;
        }

        public Criteria andCommnameNotBetween(String value1, String value2) {
            addCriterion("COMMNAME not between", value1, value2, "commname");
            return (Criteria) this;
        }

        public Criteria andCommtypeIsNull() {
            addCriterion("COMMTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCommtypeIsNotNull() {
            addCriterion("COMMTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCommtypeEqualTo(String value) {
            addCriterion("COMMTYPE =", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeNotEqualTo(String value) {
            addCriterion("COMMTYPE <>", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeGreaterThan(String value) {
            addCriterion("COMMTYPE >", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeGreaterThanOrEqualTo(String value) {
            addCriterion("COMMTYPE >=", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeLessThan(String value) {
            addCriterion("COMMTYPE <", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeLessThanOrEqualTo(String value) {
            addCriterion("COMMTYPE <=", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeLike(String value) {
            addCriterion("COMMTYPE like", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeNotLike(String value) {
            addCriterion("COMMTYPE not like", value, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeIn(List<String> values) {
            addCriterion("COMMTYPE in", values, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeNotIn(List<String> values) {
            addCriterion("COMMTYPE not in", values, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeBetween(String value1, String value2) {
            addCriterion("COMMTYPE between", value1, value2, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeNotBetween(String value1, String value2) {
            addCriterion("COMMTYPE not between", value1, value2, "commtype");
            return (Criteria) this;
        }

        public Criteria andAddrIsNull() {
            addCriterion("ADDR is null");
            return (Criteria) this;
        }

        public Criteria andAddrIsNotNull() {
            addCriterion("ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andAddrEqualTo(String value) {
            addCriterion("ADDR =", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotEqualTo(String value) {
            addCriterion("ADDR <>", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThan(String value) {
            addCriterion("ADDR >", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ADDR >=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThan(String value) {
            addCriterion("ADDR <", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThanOrEqualTo(String value) {
            addCriterion("ADDR <=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLike(String value) {
            addCriterion("ADDR like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotLike(String value) {
            addCriterion("ADDR not like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrIn(List<String> values) {
            addCriterion("ADDR in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotIn(List<String> values) {
            addCriterion("ADDR not in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrBetween(String value1, String value2) {
            addCriterion("ADDR between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotBetween(String value1, String value2) {
            addCriterion("ADDR not between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("NUM is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("NUM is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("NUM =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("NUM <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("NUM >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("NUM >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("NUM <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("NUM <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("NUM like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("NUM not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("NUM in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("NUM not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("NUM between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("NUM not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtIsNull() {
            addCriterion("RECEIVEAMT is null");
            return (Criteria) this;
        }

        public Criteria andReceiveamtIsNotNull() {
            addCriterion("RECEIVEAMT is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveamtEqualTo(BigDecimal value) {
            addCriterion("RECEIVEAMT =", value, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtNotEqualTo(BigDecimal value) {
            addCriterion("RECEIVEAMT <>", value, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtGreaterThan(BigDecimal value) {
            addCriterion("RECEIVEAMT >", value, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RECEIVEAMT >=", value, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtLessThan(BigDecimal value) {
            addCriterion("RECEIVEAMT <", value, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RECEIVEAMT <=", value, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtIn(List<BigDecimal> values) {
            addCriterion("RECEIVEAMT in", values, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtNotIn(List<BigDecimal> values) {
            addCriterion("RECEIVEAMT not in", values, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECEIVEAMT between", value1, value2, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andReceiveamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RECEIVEAMT not between", value1, value2, "receiveamt");
            return (Criteria) this;
        }

        public Criteria andAppamtIsNull() {
            addCriterion("APPAMT is null");
            return (Criteria) this;
        }

        public Criteria andAppamtIsNotNull() {
            addCriterion("APPAMT is not null");
            return (Criteria) this;
        }

        public Criteria andAppamtEqualTo(BigDecimal value) {
            addCriterion("APPAMT =", value, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtNotEqualTo(BigDecimal value) {
            addCriterion("APPAMT <>", value, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtGreaterThan(BigDecimal value) {
            addCriterion("APPAMT >", value, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APPAMT >=", value, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtLessThan(BigDecimal value) {
            addCriterion("APPAMT <", value, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APPAMT <=", value, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtIn(List<BigDecimal> values) {
            addCriterion("APPAMT in", values, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtNotIn(List<BigDecimal> values) {
            addCriterion("APPAMT not in", values, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPAMT between", value1, value2, "appamt");
            return (Criteria) this;
        }

        public Criteria andAppamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPAMT not between", value1, value2, "appamt");
            return (Criteria) this;
        }

        public Criteria andDividIsNull() {
            addCriterion("DIVID is null");
            return (Criteria) this;
        }

        public Criteria andDividIsNotNull() {
            addCriterion("DIVID is not null");
            return (Criteria) this;
        }

        public Criteria andDividEqualTo(String value) {
            addCriterion("DIVID =", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividNotEqualTo(String value) {
            addCriterion("DIVID <>", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividGreaterThan(String value) {
            addCriterion("DIVID >", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividGreaterThanOrEqualTo(String value) {
            addCriterion("DIVID >=", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividLessThan(String value) {
            addCriterion("DIVID <", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividLessThanOrEqualTo(String value) {
            addCriterion("DIVID <=", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividLike(String value) {
            addCriterion("DIVID like", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividNotLike(String value) {
            addCriterion("DIVID not like", value, "divid");
            return (Criteria) this;
        }

        public Criteria andDividIn(List<String> values) {
            addCriterion("DIVID in", values, "divid");
            return (Criteria) this;
        }

        public Criteria andDividNotIn(List<String> values) {
            addCriterion("DIVID not in", values, "divid");
            return (Criteria) this;
        }

        public Criteria andDividBetween(String value1, String value2) {
            addCriterion("DIVID between", value1, value2, "divid");
            return (Criteria) this;
        }

        public Criteria andDividNotBetween(String value1, String value2) {
            addCriterion("DIVID not between", value1, value2, "divid");
            return (Criteria) this;
        }

        public Criteria andCommissionrateIsNull() {
            addCriterion("COMMISSIONRATE is null");
            return (Criteria) this;
        }

        public Criteria andCommissionrateIsNotNull() {
            addCriterion("COMMISSIONRATE is not null");
            return (Criteria) this;
        }

        public Criteria andCommissionrateEqualTo(BigDecimal value) {
            addCriterion("COMMISSIONRATE =", value, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateNotEqualTo(BigDecimal value) {
            addCriterion("COMMISSIONRATE <>", value, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateGreaterThan(BigDecimal value) {
            addCriterion("COMMISSIONRATE >", value, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COMMISSIONRATE >=", value, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateLessThan(BigDecimal value) {
            addCriterion("COMMISSIONRATE <", value, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COMMISSIONRATE <=", value, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateIn(List<BigDecimal> values) {
            addCriterion("COMMISSIONRATE in", values, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateNotIn(List<BigDecimal> values) {
            addCriterion("COMMISSIONRATE not in", values, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMMISSIONRATE between", value1, value2, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCommissionrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COMMISSIONRATE not between", value1, value2, "commissionrate");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoIsNull() {
            addCriterion("CMLOANACTNO is null");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoIsNotNull() {
            addCriterion("CMLOANACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoEqualTo(String value) {
            addCriterion("CMLOANACTNO =", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoNotEqualTo(String value) {
            addCriterion("CMLOANACTNO <>", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoGreaterThan(String value) {
            addCriterion("CMLOANACTNO >", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoGreaterThanOrEqualTo(String value) {
            addCriterion("CMLOANACTNO >=", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoLessThan(String value) {
            addCriterion("CMLOANACTNO <", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoLessThanOrEqualTo(String value) {
            addCriterion("CMLOANACTNO <=", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoLike(String value) {
            addCriterion("CMLOANACTNO like", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoNotLike(String value) {
            addCriterion("CMLOANACTNO not like", value, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoIn(List<String> values) {
            addCriterion("CMLOANACTNO in", values, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoNotIn(List<String> values) {
            addCriterion("CMLOANACTNO not in", values, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoBetween(String value1, String value2) {
            addCriterion("CMLOANACTNO between", value1, value2, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andCmloanactnoNotBetween(String value1, String value2) {
            addCriterion("CMLOANACTNO not between", value1, value2, "cmloanactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoIsNull() {
            addCriterion("DBDEPOACTNO is null");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoIsNotNull() {
            addCriterion("DBDEPOACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoEqualTo(String value) {
            addCriterion("DBDEPOACTNO =", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoNotEqualTo(String value) {
            addCriterion("DBDEPOACTNO <>", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoGreaterThan(String value) {
            addCriterion("DBDEPOACTNO >", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoGreaterThanOrEqualTo(String value) {
            addCriterion("DBDEPOACTNO >=", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoLessThan(String value) {
            addCriterion("DBDEPOACTNO <", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoLessThanOrEqualTo(String value) {
            addCriterion("DBDEPOACTNO <=", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoLike(String value) {
            addCriterion("DBDEPOACTNO like", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoNotLike(String value) {
            addCriterion("DBDEPOACTNO not like", value, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoIn(List<String> values) {
            addCriterion("DBDEPOACTNO in", values, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoNotIn(List<String> values) {
            addCriterion("DBDEPOACTNO not in", values, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoBetween(String value1, String value2) {
            addCriterion("DBDEPOACTNO between", value1, value2, "dbdepoactno");
            return (Criteria) this;
        }

        public Criteria andDbdepoactnoNotBetween(String value1, String value2) {
            addCriterion("DBDEPOACTNO not between", value1, value2, "dbdepoactno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 13 21:38:48 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIP.XFAPPCOMM
     *
     * @mbggenerated Sat Aug 13 21:38:48 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}