package fip.repository.model;

import java.math.BigDecimal;

public class Xfgrademark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFGRADEMARK.SEQNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private BigDecimal seqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFGRADEMARK.ENUMTP
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String enumtp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFGRADEMARK.ENUMVAL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String enumval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFGRADEMARK.CONDITION
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFGRADEMARK.GRADE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XFGRADEMARK.SAMPLE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    private String sample;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFGRADEMARK.SEQNO
     *
     * @return the value of XFGRADEMARK.SEQNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public BigDecimal getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFGRADEMARK.SEQNO
     *
     * @param seqno the value for XFGRADEMARK.SEQNO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setSeqno(BigDecimal seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFGRADEMARK.ENUMTP
     *
     * @return the value of XFGRADEMARK.ENUMTP
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getEnumtp() {
        return enumtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFGRADEMARK.ENUMTP
     *
     * @param enumtp the value for XFGRADEMARK.ENUMTP
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setEnumtp(String enumtp) {
        this.enumtp = enumtp == null ? null : enumtp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFGRADEMARK.ENUMVAL
     *
     * @return the value of XFGRADEMARK.ENUMVAL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getEnumval() {
        return enumval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFGRADEMARK.ENUMVAL
     *
     * @param enumval the value for XFGRADEMARK.ENUMVAL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setEnumval(String enumval) {
        this.enumval = enumval == null ? null : enumval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFGRADEMARK.CONDITION
     *
     * @return the value of XFGRADEMARK.CONDITION
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFGRADEMARK.CONDITION
     *
     * @param condition the value for XFGRADEMARK.CONDITION
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFGRADEMARK.GRADE
     *
     * @return the value of XFGRADEMARK.GRADE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFGRADEMARK.GRADE
     *
     * @param grade the value for XFGRADEMARK.GRADE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XFGRADEMARK.SAMPLE
     *
     * @return the value of XFGRADEMARK.SAMPLE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XFGRADEMARK.SAMPLE
     *
     * @param sample the value for XFGRADEMARK.SAMPLE
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setSample(String sample) {
        this.sample = sample == null ? null : sample.trim();
    }
}