package fip.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XfifbankdetlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public XfifbankdetlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJournalnoIsNull() {
            addCriterion("JOURNALNO is null");
            return (Criteria) this;
        }

        public Criteria andJournalnoIsNotNull() {
            addCriterion("JOURNALNO is not null");
            return (Criteria) this;
        }

        public Criteria andJournalnoEqualTo(String value) {
            addCriterion("JOURNALNO =", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoNotEqualTo(String value) {
            addCriterion("JOURNALNO <>", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoGreaterThan(String value) {
            addCriterion("JOURNALNO >", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoGreaterThanOrEqualTo(String value) {
            addCriterion("JOURNALNO >=", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoLessThan(String value) {
            addCriterion("JOURNALNO <", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoLessThanOrEqualTo(String value) {
            addCriterion("JOURNALNO <=", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoLike(String value) {
            addCriterion("JOURNALNO like", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoNotLike(String value) {
            addCriterion("JOURNALNO not like", value, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoIn(List<String> values) {
            addCriterion("JOURNALNO in", values, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoNotIn(List<String> values) {
            addCriterion("JOURNALNO not in", values, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoBetween(String value1, String value2) {
            addCriterion("JOURNALNO between", value1, value2, "journalno");
            return (Criteria) this;
        }

        public Criteria andJournalnoNotBetween(String value1, String value2) {
            addCriterion("JOURNALNO not between", value1, value2, "journalno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoIsNull() {
            addCriterion("BIZSEQNO is null");
            return (Criteria) this;
        }

        public Criteria andBizseqnoIsNotNull() {
            addCriterion("BIZSEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andBizseqnoEqualTo(String value) {
            addCriterion("BIZSEQNO =", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoNotEqualTo(String value) {
            addCriterion("BIZSEQNO <>", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoGreaterThan(String value) {
            addCriterion("BIZSEQNO >", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoGreaterThanOrEqualTo(String value) {
            addCriterion("BIZSEQNO >=", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoLessThan(String value) {
            addCriterion("BIZSEQNO <", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoLessThanOrEqualTo(String value) {
            addCriterion("BIZSEQNO <=", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoLike(String value) {
            addCriterion("BIZSEQNO like", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoNotLike(String value) {
            addCriterion("BIZSEQNO not like", value, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoIn(List<String> values) {
            addCriterion("BIZSEQNO in", values, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoNotIn(List<String> values) {
            addCriterion("BIZSEQNO not in", values, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoBetween(String value1, String value2) {
            addCriterion("BIZSEQNO between", value1, value2, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andBizseqnoNotBetween(String value1, String value2) {
            addCriterion("BIZSEQNO not between", value1, value2, "bizseqno");
            return (Criteria) this;
        }

        public Criteria andTxndateIsNull() {
            addCriterion("TXNDATE is null");
            return (Criteria) this;
        }

        public Criteria andTxndateIsNotNull() {
            addCriterion("TXNDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxndateEqualTo(String value) {
            addCriterion("TXNDATE =", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateNotEqualTo(String value) {
            addCriterion("TXNDATE <>", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateGreaterThan(String value) {
            addCriterion("TXNDATE >", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateGreaterThanOrEqualTo(String value) {
            addCriterion("TXNDATE >=", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateLessThan(String value) {
            addCriterion("TXNDATE <", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateLessThanOrEqualTo(String value) {
            addCriterion("TXNDATE <=", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateLike(String value) {
            addCriterion("TXNDATE like", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateNotLike(String value) {
            addCriterion("TXNDATE not like", value, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateIn(List<String> values) {
            addCriterion("TXNDATE in", values, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateNotIn(List<String> values) {
            addCriterion("TXNDATE not in", values, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateBetween(String value1, String value2) {
            addCriterion("TXNDATE between", value1, value2, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxndateNotBetween(String value1, String value2) {
            addCriterion("TXNDATE not between", value1, value2, "txndate");
            return (Criteria) this;
        }

        public Criteria andTxntypeIsNull() {
            addCriterion("TXNTYPE is null");
            return (Criteria) this;
        }

        public Criteria andTxntypeIsNotNull() {
            addCriterion("TXNTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTxntypeEqualTo(String value) {
            addCriterion("TXNTYPE =", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotEqualTo(String value) {
            addCriterion("TXNTYPE <>", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeGreaterThan(String value) {
            addCriterion("TXNTYPE >", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeGreaterThanOrEqualTo(String value) {
            addCriterion("TXNTYPE >=", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeLessThan(String value) {
            addCriterion("TXNTYPE <", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeLessThanOrEqualTo(String value) {
            addCriterion("TXNTYPE <=", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeLike(String value) {
            addCriterion("TXNTYPE like", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotLike(String value) {
            addCriterion("TXNTYPE not like", value, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeIn(List<String> values) {
            addCriterion("TXNTYPE in", values, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotIn(List<String> values) {
            addCriterion("TXNTYPE not in", values, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeBetween(String value1, String value2) {
            addCriterion("TXNTYPE between", value1, value2, "txntype");
            return (Criteria) this;
        }

        public Criteria andTxntypeNotBetween(String value1, String value2) {
            addCriterion("TXNTYPE not between", value1, value2, "txntype");
            return (Criteria) this;
        }

        public Criteria andTotalcountIsNull() {
            addCriterion("TOTALCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalcountIsNotNull() {
            addCriterion("TOTALCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalcountEqualTo(BigDecimal value) {
            addCriterion("TOTALCOUNT =", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotEqualTo(BigDecimal value) {
            addCriterion("TOTALCOUNT <>", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountGreaterThan(BigDecimal value) {
            addCriterion("TOTALCOUNT >", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCOUNT >=", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountLessThan(BigDecimal value) {
            addCriterion("TOTALCOUNT <", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALCOUNT <=", value, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountIn(List<BigDecimal> values) {
            addCriterion("TOTALCOUNT in", values, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotIn(List<BigDecimal> values) {
            addCriterion("TOTALCOUNT not in", values, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCOUNT between", value1, value2, "totalcount");
            return (Criteria) this;
        }

        public Criteria andTotalcountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALCOUNT not between", value1, value2, "totalcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountIsNull() {
            addCriterion("CURRCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCurrcountIsNotNull() {
            addCriterion("CURRCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCurrcountEqualTo(BigDecimal value) {
            addCriterion("CURRCOUNT =", value, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountNotEqualTo(BigDecimal value) {
            addCriterion("CURRCOUNT <>", value, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountGreaterThan(BigDecimal value) {
            addCriterion("CURRCOUNT >", value, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CURRCOUNT >=", value, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountLessThan(BigDecimal value) {
            addCriterion("CURRCOUNT <", value, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CURRCOUNT <=", value, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountIn(List<BigDecimal> values) {
            addCriterion("CURRCOUNT in", values, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountNotIn(List<BigDecimal> values) {
            addCriterion("CURRCOUNT not in", values, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURRCOUNT between", value1, value2, "currcount");
            return (Criteria) this;
        }

        public Criteria andCurrcountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CURRCOUNT not between", value1, value2, "currcount");
            return (Criteria) this;
        }

        public Criteria andMultiflagIsNull() {
            addCriterion("MULTIFLAG is null");
            return (Criteria) this;
        }

        public Criteria andMultiflagIsNotNull() {
            addCriterion("MULTIFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andMultiflagEqualTo(String value) {
            addCriterion("MULTIFLAG =", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagNotEqualTo(String value) {
            addCriterion("MULTIFLAG <>", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagGreaterThan(String value) {
            addCriterion("MULTIFLAG >", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagGreaterThanOrEqualTo(String value) {
            addCriterion("MULTIFLAG >=", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagLessThan(String value) {
            addCriterion("MULTIFLAG <", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagLessThanOrEqualTo(String value) {
            addCriterion("MULTIFLAG <=", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagLike(String value) {
            addCriterion("MULTIFLAG like", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagNotLike(String value) {
            addCriterion("MULTIFLAG not like", value, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagIn(List<String> values) {
            addCriterion("MULTIFLAG in", values, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagNotIn(List<String> values) {
            addCriterion("MULTIFLAG not in", values, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagBetween(String value1, String value2) {
            addCriterion("MULTIFLAG between", value1, value2, "multiflag");
            return (Criteria) this;
        }

        public Criteria andMultiflagNotBetween(String value1, String value2) {
            addCriterion("MULTIFLAG not between", value1, value2, "multiflag");
            return (Criteria) this;
        }

        public Criteria andTransferactIsNull() {
            addCriterion("TRANSFERACT is null");
            return (Criteria) this;
        }

        public Criteria andTransferactIsNotNull() {
            addCriterion("TRANSFERACT is not null");
            return (Criteria) this;
        }

        public Criteria andTransferactEqualTo(String value) {
            addCriterion("TRANSFERACT =", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactNotEqualTo(String value) {
            addCriterion("TRANSFERACT <>", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactGreaterThan(String value) {
            addCriterion("TRANSFERACT >", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFERACT >=", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactLessThan(String value) {
            addCriterion("TRANSFERACT <", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactLessThanOrEqualTo(String value) {
            addCriterion("TRANSFERACT <=", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactLike(String value) {
            addCriterion("TRANSFERACT like", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactNotLike(String value) {
            addCriterion("TRANSFERACT not like", value, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactIn(List<String> values) {
            addCriterion("TRANSFERACT in", values, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactNotIn(List<String> values) {
            addCriterion("TRANSFERACT not in", values, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactBetween(String value1, String value2) {
            addCriterion("TRANSFERACT between", value1, value2, "transferact");
            return (Criteria) this;
        }

        public Criteria andTransferactNotBetween(String value1, String value2) {
            addCriterion("TRANSFERACT not between", value1, value2, "transferact");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNull() {
            addCriterion("TOTALAMT is null");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNotNull() {
            addCriterion("TOTALAMT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalamtEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT =", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT <>", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThan(BigDecimal value) {
            addCriterion("TOTALAMT >", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT >=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThan(BigDecimal value) {
            addCriterion("TOTALAMT <", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT <=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtIn(List<BigDecimal> values) {
            addCriterion("TOTALAMT in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotIn(List<BigDecimal> values) {
            addCriterion("TOTALAMT not in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALAMT between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALAMT not between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andFailamtIsNull() {
            addCriterion("FAILAMT is null");
            return (Criteria) this;
        }

        public Criteria andFailamtIsNotNull() {
            addCriterion("FAILAMT is not null");
            return (Criteria) this;
        }

        public Criteria andFailamtEqualTo(BigDecimal value) {
            addCriterion("FAILAMT =", value, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtNotEqualTo(BigDecimal value) {
            addCriterion("FAILAMT <>", value, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtGreaterThan(BigDecimal value) {
            addCriterion("FAILAMT >", value, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FAILAMT >=", value, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtLessThan(BigDecimal value) {
            addCriterion("FAILAMT <", value, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FAILAMT <=", value, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtIn(List<BigDecimal> values) {
            addCriterion("FAILAMT in", values, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtNotIn(List<BigDecimal> values) {
            addCriterion("FAILAMT not in", values, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAILAMT between", value1, value2, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAILAMT not between", value1, value2, "failamt");
            return (Criteria) this;
        }

        public Criteria andFailcountIsNull() {
            addCriterion("FAILCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andFailcountIsNotNull() {
            addCriterion("FAILCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFailcountEqualTo(BigDecimal value) {
            addCriterion("FAILCOUNT =", value, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountNotEqualTo(BigDecimal value) {
            addCriterion("FAILCOUNT <>", value, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountGreaterThan(BigDecimal value) {
            addCriterion("FAILCOUNT >", value, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FAILCOUNT >=", value, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountLessThan(BigDecimal value) {
            addCriterion("FAILCOUNT <", value, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FAILCOUNT <=", value, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountIn(List<BigDecimal> values) {
            addCriterion("FAILCOUNT in", values, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountNotIn(List<BigDecimal> values) {
            addCriterion("FAILCOUNT not in", values, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAILCOUNT between", value1, value2, "failcount");
            return (Criteria) this;
        }

        public Criteria andFailcountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FAILCOUNT not between", value1, value2, "failcount");
            return (Criteria) this;
        }

        public Criteria andUsageIsNull() {
            addCriterion("USAGE is null");
            return (Criteria) this;
        }

        public Criteria andUsageIsNotNull() {
            addCriterion("USAGE is not null");
            return (Criteria) this;
        }

        public Criteria andUsageEqualTo(String value) {
            addCriterion("USAGE =", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotEqualTo(String value) {
            addCriterion("USAGE <>", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageGreaterThan(String value) {
            addCriterion("USAGE >", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageGreaterThanOrEqualTo(String value) {
            addCriterion("USAGE >=", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLessThan(String value) {
            addCriterion("USAGE <", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLessThanOrEqualTo(String value) {
            addCriterion("USAGE <=", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLike(String value) {
            addCriterion("USAGE like", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotLike(String value) {
            addCriterion("USAGE not like", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageIn(List<String> values) {
            addCriterion("USAGE in", values, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotIn(List<String> values) {
            addCriterion("USAGE not in", values, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageBetween(String value1, String value2) {
            addCriterion("USAGE between", value1, value2, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotBetween(String value1, String value2) {
            addCriterion("USAGE not between", value1, value2, "usage");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNull() {
            addCriterion("REMARK1 is null");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNotNull() {
            addCriterion("REMARK1 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark1EqualTo(String value) {
            addCriterion("REMARK1 =", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotEqualTo(String value) {
            addCriterion("REMARK1 <>", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThan(String value) {
            addCriterion("REMARK1 >", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK1 >=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThan(String value) {
            addCriterion("REMARK1 <", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThanOrEqualTo(String value) {
            addCriterion("REMARK1 <=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Like(String value) {
            addCriterion("REMARK1 like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotLike(String value) {
            addCriterion("REMARK1 not like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1In(List<String> values) {
            addCriterion("REMARK1 in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotIn(List<String> values) {
            addCriterion("REMARK1 not in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Between(String value1, String value2) {
            addCriterion("REMARK1 between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotBetween(String value1, String value2) {
            addCriterion("REMARK1 not between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNull() {
            addCriterion("REMARK2 is null");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNotNull() {
            addCriterion("REMARK2 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark2EqualTo(String value) {
            addCriterion("REMARK2 =", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotEqualTo(String value) {
            addCriterion("REMARK2 <>", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThan(String value) {
            addCriterion("REMARK2 >", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK2 >=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThan(String value) {
            addCriterion("REMARK2 <", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThanOrEqualTo(String value) {
            addCriterion("REMARK2 <=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Like(String value) {
            addCriterion("REMARK2 like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotLike(String value) {
            addCriterion("REMARK2 not like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2In(List<String> values) {
            addCriterion("REMARK2 in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotIn(List<String> values) {
            addCriterion("REMARK2 not in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Between(String value1, String value2) {
            addCriterion("REMARK2 between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotBetween(String value1, String value2) {
            addCriterion("REMARK2 not between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterion("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterion("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterion("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterion("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterion("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterion("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterion("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterion("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterion("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andBankidIsNull() {
            addCriterion("BANKID is null");
            return (Criteria) this;
        }

        public Criteria andBankidIsNotNull() {
            addCriterion("BANKID is not null");
            return (Criteria) this;
        }

        public Criteria andBankidEqualTo(String value) {
            addCriterion("BANKID =", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotEqualTo(String value) {
            addCriterion("BANKID <>", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidGreaterThan(String value) {
            addCriterion("BANKID >", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidGreaterThanOrEqualTo(String value) {
            addCriterion("BANKID >=", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLessThan(String value) {
            addCriterion("BANKID <", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLessThanOrEqualTo(String value) {
            addCriterion("BANKID <=", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLike(String value) {
            addCriterion("BANKID like", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotLike(String value) {
            addCriterion("BANKID not like", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidIn(List<String> values) {
            addCriterion("BANKID in", values, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotIn(List<String> values) {
            addCriterion("BANKID not in", values, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidBetween(String value1, String value2) {
            addCriterion("BANKID between", value1, value2, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotBetween(String value1, String value2) {
            addCriterion("BANKID not between", value1, value2, "bankid");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIsNull() {
            addCriterion("SYSTEMTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIsNotNull() {
            addCriterion("SYSTEMTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSystemtypeEqualTo(String value) {
            addCriterion("SYSTEMTYPE =", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotEqualTo(String value) {
            addCriterion("SYSTEMTYPE <>", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeGreaterThan(String value) {
            addCriterion("SYSTEMTYPE >", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMTYPE >=", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLessThan(String value) {
            addCriterion("SYSTEMTYPE <", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMTYPE <=", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLike(String value) {
            addCriterion("SYSTEMTYPE like", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotLike(String value) {
            addCriterion("SYSTEMTYPE not like", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIn(List<String> values) {
            addCriterion("SYSTEMTYPE in", values, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotIn(List<String> values) {
            addCriterion("SYSTEMTYPE not in", values, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeBetween(String value1, String value2) {
            addCriterion("SYSTEMTYPE between", value1, value2, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotBetween(String value1, String value2) {
            addCriterion("SYSTEMTYPE not between", value1, value2, "systemtype");
            return (Criteria) this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("OPERATORID is null");
            return (Criteria) this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("OPERATORID is not null");
            return (Criteria) this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("OPERATORID =", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("OPERATORID <>", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("OPERATORID >", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATORID >=", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("OPERATORID <", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("OPERATORID <=", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("OPERATORID like", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("OPERATORID not like", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("OPERATORID in", values, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("OPERATORID not in", values, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("OPERATORID between", value1, value2, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("OPERATORID not between", value1, value2, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatedateIsNull() {
            addCriterion("OPERATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperatedateIsNotNull() {
            addCriterion("OPERATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperatedateEqualTo(Date value) {
            addCriterion("OPERATEDATE =", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotEqualTo(Date value) {
            addCriterion("OPERATEDATE <>", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateGreaterThan(Date value) {
            addCriterion("OPERATEDATE >", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERATEDATE >=", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateLessThan(Date value) {
            addCriterion("OPERATEDATE <", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateLessThanOrEqualTo(Date value) {
            addCriterion("OPERATEDATE <=", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateIn(List<Date> values) {
            addCriterion("OPERATEDATE in", values, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotIn(List<Date> values) {
            addCriterion("OPERATEDATE not in", values, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateBetween(Date value1, Date value2) {
            addCriterion("OPERATEDATE between", value1, value2, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotBetween(Date value1, Date value2) {
            addCriterion("OPERATEDATE not between", value1, value2, "operatedate");
            return (Criteria) this;
        }

        public Criteria andCheckeridIsNull() {
            addCriterion("CHECKERID is null");
            return (Criteria) this;
        }

        public Criteria andCheckeridIsNotNull() {
            addCriterion("CHECKERID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckeridEqualTo(String value) {
            addCriterion("CHECKERID =", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotEqualTo(String value) {
            addCriterion("CHECKERID <>", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridGreaterThan(String value) {
            addCriterion("CHECKERID >", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKERID >=", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridLessThan(String value) {
            addCriterion("CHECKERID <", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridLessThanOrEqualTo(String value) {
            addCriterion("CHECKERID <=", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridLike(String value) {
            addCriterion("CHECKERID like", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotLike(String value) {
            addCriterion("CHECKERID not like", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridIn(List<String> values) {
            addCriterion("CHECKERID in", values, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotIn(List<String> values) {
            addCriterion("CHECKERID not in", values, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridBetween(String value1, String value2) {
            addCriterion("CHECKERID between", value1, value2, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotBetween(String value1, String value2) {
            addCriterion("CHECKERID not between", value1, value2, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNull() {
            addCriterion("CHECKDATE is null");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNotNull() {
            addCriterion("CHECKDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckdateEqualTo(Date value) {
            addCriterion("CHECKDATE =", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotEqualTo(Date value) {
            addCriterion("CHECKDATE <>", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThan(Date value) {
            addCriterion("CHECKDATE >", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThanOrEqualTo(Date value) {
            addCriterion("CHECKDATE >=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThan(Date value) {
            addCriterion("CHECKDATE <", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThanOrEqualTo(Date value) {
            addCriterion("CHECKDATE <=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateIn(List<Date> values) {
            addCriterion("CHECKDATE in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotIn(List<Date> values) {
            addCriterion("CHECKDATE not in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateBetween(Date value1, Date value2) {
            addCriterion("CHECKDATE between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotBetween(Date value1, Date value2) {
            addCriterion("CHECKDATE not between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("CREATORID is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("CREATORID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("CREATORID =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("CREATORID <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("CREATORID >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORID >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("CREATORID <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("CREATORID <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("CREATORID like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("CREATORID not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("CREATORID in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("CREATORID not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("CREATORID between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("CREATORID not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreateformIsNull() {
            addCriterion("CREATEFORM is null");
            return (Criteria) this;
        }

        public Criteria andCreateformIsNotNull() {
            addCriterion("CREATEFORM is not null");
            return (Criteria) this;
        }

        public Criteria andCreateformEqualTo(String value) {
            addCriterion("CREATEFORM =", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotEqualTo(String value) {
            addCriterion("CREATEFORM <>", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformGreaterThan(String value) {
            addCriterion("CREATEFORM >", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEFORM >=", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformLessThan(String value) {
            addCriterion("CREATEFORM <", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformLessThanOrEqualTo(String value) {
            addCriterion("CREATEFORM <=", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformLike(String value) {
            addCriterion("CREATEFORM like", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotLike(String value) {
            addCriterion("CREATEFORM not like", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformIn(List<String> values) {
            addCriterion("CREATEFORM in", values, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotIn(List<String> values) {
            addCriterion("CREATEFORM not in", values, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformBetween(String value1, String value2) {
            addCriterion("CREATEFORM between", value1, value2, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotBetween(String value1, String value2) {
            addCriterion("CREATEFORM not between", value1, value2, "createform");
            return (Criteria) this;
        }

        public Criteria andUpdatoridIsNull() {
            addCriterion("UPDATORID is null");
            return (Criteria) this;
        }

        public Criteria andUpdatoridIsNotNull() {
            addCriterion("UPDATORID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatoridEqualTo(String value) {
            addCriterion("UPDATORID =", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotEqualTo(String value) {
            addCriterion("UPDATORID <>", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridGreaterThan(String value) {
            addCriterion("UPDATORID >", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATORID >=", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridLessThan(String value) {
            addCriterion("UPDATORID <", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridLessThanOrEqualTo(String value) {
            addCriterion("UPDATORID <=", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridLike(String value) {
            addCriterion("UPDATORID like", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotLike(String value) {
            addCriterion("UPDATORID not like", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridIn(List<String> values) {
            addCriterion("UPDATORID in", values, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotIn(List<String> values) {
            addCriterion("UPDATORID not in", values, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridBetween(String value1, String value2) {
            addCriterion("UPDATORID between", value1, value2, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotBetween(String value1, String value2) {
            addCriterion("UPDATORID not between", value1, value2, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("UPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("UPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("UPDATEDATE =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("UPDATEDATE <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("UPDATEDATE >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("UPDATEDATE <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("UPDATEDATE in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("UPDATEDATE not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdateformIsNull() {
            addCriterion("UPDATEFORM is null");
            return (Criteria) this;
        }

        public Criteria andUpdateformIsNotNull() {
            addCriterion("UPDATEFORM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateformEqualTo(String value) {
            addCriterion("UPDATEFORM =", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotEqualTo(String value) {
            addCriterion("UPDATEFORM <>", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformGreaterThan(String value) {
            addCriterion("UPDATEFORM >", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEFORM >=", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformLessThan(String value) {
            addCriterion("UPDATEFORM <", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformLessThanOrEqualTo(String value) {
            addCriterion("UPDATEFORM <=", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformLike(String value) {
            addCriterion("UPDATEFORM like", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotLike(String value) {
            addCriterion("UPDATEFORM not like", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformIn(List<String> values) {
            addCriterion("UPDATEFORM in", values, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotIn(List<String> values) {
            addCriterion("UPDATEFORM not in", values, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformBetween(String value1, String value2) {
            addCriterion("UPDATEFORM between", value1, value2, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotBetween(String value1, String value2) {
            addCriterion("UPDATEFORM not between", value1, value2, "updateform");
            return (Criteria) this;
        }

        public Criteria andLogIsNull() {
            addCriterion("LOG is null");
            return (Criteria) this;
        }

        public Criteria andLogIsNotNull() {
            addCriterion("LOG is not null");
            return (Criteria) this;
        }

        public Criteria andLogEqualTo(String value) {
            addCriterion("LOG =", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogNotEqualTo(String value) {
            addCriterion("LOG <>", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogGreaterThan(String value) {
            addCriterion("LOG >", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogGreaterThanOrEqualTo(String value) {
            addCriterion("LOG >=", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogLessThan(String value) {
            addCriterion("LOG <", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogLessThanOrEqualTo(String value) {
            addCriterion("LOG <=", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogLike(String value) {
            addCriterion("LOG like", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogNotLike(String value) {
            addCriterion("LOG not like", value, "log");
            return (Criteria) this;
        }

        public Criteria andLogIn(List<String> values) {
            addCriterion("LOG in", values, "log");
            return (Criteria) this;
        }

        public Criteria andLogNotIn(List<String> values) {
            addCriterion("LOG not in", values, "log");
            return (Criteria) this;
        }

        public Criteria andLogBetween(String value1, String value2) {
            addCriterion("LOG between", value1, value2, "log");
            return (Criteria) this;
        }

        public Criteria andLogNotBetween(String value1, String value2) {
            addCriterion("LOG not between", value1, value2, "log");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 22 13:32:19 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XFIFBANKDETL
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}