package fip.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XfwriteoffinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public XfwriteoffinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContractnoIsNull() {
            addCriterion("CONTRACTNO is null");
            return (Criteria) this;
        }

        public Criteria andContractnoIsNotNull() {
            addCriterion("CONTRACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andContractnoEqualTo(String value) {
            addCriterion("CONTRACTNO =", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoNotEqualTo(String value) {
            addCriterion("CONTRACTNO <>", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoGreaterThan(String value) {
            addCriterion("CONTRACTNO >", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACTNO >=", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoLessThan(String value) {
            addCriterion("CONTRACTNO <", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoLessThanOrEqualTo(String value) {
            addCriterion("CONTRACTNO <=", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoLike(String value) {
            addCriterion("CONTRACTNO like", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoNotLike(String value) {
            addCriterion("CONTRACTNO not like", value, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoIn(List<String> values) {
            addCriterion("CONTRACTNO in", values, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoNotIn(List<String> values) {
            addCriterion("CONTRACTNO not in", values, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoBetween(String value1, String value2) {
            addCriterion("CONTRACTNO between", value1, value2, "contractno");
            return (Criteria) this;
        }

        public Criteria andContractnoNotBetween(String value1, String value2) {
            addCriterion("CONTRACTNO not between", value1, value2, "contractno");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusIsNull() {
            addCriterion("WRITEOFFSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusIsNotNull() {
            addCriterion("WRITEOFFSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusEqualTo(String value) {
            addCriterion("WRITEOFFSTATUS =", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusNotEqualTo(String value) {
            addCriterion("WRITEOFFSTATUS <>", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusGreaterThan(String value) {
            addCriterion("WRITEOFFSTATUS >", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusGreaterThanOrEqualTo(String value) {
            addCriterion("WRITEOFFSTATUS >=", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusLessThan(String value) {
            addCriterion("WRITEOFFSTATUS <", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusLessThanOrEqualTo(String value) {
            addCriterion("WRITEOFFSTATUS <=", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusLike(String value) {
            addCriterion("WRITEOFFSTATUS like", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusNotLike(String value) {
            addCriterion("WRITEOFFSTATUS not like", value, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusIn(List<String> values) {
            addCriterion("WRITEOFFSTATUS in", values, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusNotIn(List<String> values) {
            addCriterion("WRITEOFFSTATUS not in", values, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusBetween(String value1, String value2) {
            addCriterion("WRITEOFFSTATUS between", value1, value2, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andWriteoffstatusNotBetween(String value1, String value2) {
            addCriterion("WRITEOFFSTATUS not between", value1, value2, "writeoffstatus");
            return (Criteria) this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("OPERATORID is null");
            return (Criteria) this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("OPERATORID is not null");
            return (Criteria) this;
        }

        public Criteria andOperatoridEqualTo(String value) {
            addCriterion("OPERATORID =", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotEqualTo(String value) {
            addCriterion("OPERATORID <>", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridGreaterThan(String value) {
            addCriterion("OPERATORID >", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATORID >=", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridLessThan(String value) {
            addCriterion("OPERATORID <", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(String value) {
            addCriterion("OPERATORID <=", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridLike(String value) {
            addCriterion("OPERATORID like", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotLike(String value) {
            addCriterion("OPERATORID not like", value, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridIn(List<String> values) {
            addCriterion("OPERATORID in", values, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotIn(List<String> values) {
            addCriterion("OPERATORID not in", values, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridBetween(String value1, String value2) {
            addCriterion("OPERATORID between", value1, value2, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotBetween(String value1, String value2) {
            addCriterion("OPERATORID not between", value1, value2, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatedateIsNull() {
            addCriterion("OPERATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperatedateIsNotNull() {
            addCriterion("OPERATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperatedateEqualTo(Date value) {
            addCriterion("OPERATEDATE =", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotEqualTo(Date value) {
            addCriterion("OPERATEDATE <>", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateGreaterThan(Date value) {
            addCriterion("OPERATEDATE >", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERATEDATE >=", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateLessThan(Date value) {
            addCriterion("OPERATEDATE <", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateLessThanOrEqualTo(Date value) {
            addCriterion("OPERATEDATE <=", value, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateIn(List<Date> values) {
            addCriterion("OPERATEDATE in", values, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotIn(List<Date> values) {
            addCriterion("OPERATEDATE not in", values, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateBetween(Date value1, Date value2) {
            addCriterion("OPERATEDATE between", value1, value2, "operatedate");
            return (Criteria) this;
        }

        public Criteria andOperatedateNotBetween(Date value1, Date value2) {
            addCriterion("OPERATEDATE not between", value1, value2, "operatedate");
            return (Criteria) this;
        }

        public Criteria andCheckeridIsNull() {
            addCriterion("CHECKERID is null");
            return (Criteria) this;
        }

        public Criteria andCheckeridIsNotNull() {
            addCriterion("CHECKERID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckeridEqualTo(String value) {
            addCriterion("CHECKERID =", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotEqualTo(String value) {
            addCriterion("CHECKERID <>", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridGreaterThan(String value) {
            addCriterion("CHECKERID >", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKERID >=", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridLessThan(String value) {
            addCriterion("CHECKERID <", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridLessThanOrEqualTo(String value) {
            addCriterion("CHECKERID <=", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridLike(String value) {
            addCriterion("CHECKERID like", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotLike(String value) {
            addCriterion("CHECKERID not like", value, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridIn(List<String> values) {
            addCriterion("CHECKERID in", values, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotIn(List<String> values) {
            addCriterion("CHECKERID not in", values, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridBetween(String value1, String value2) {
            addCriterion("CHECKERID between", value1, value2, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckeridNotBetween(String value1, String value2) {
            addCriterion("CHECKERID not between", value1, value2, "checkerid");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNull() {
            addCriterion("CHECKDATE is null");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNotNull() {
            addCriterion("CHECKDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckdateEqualTo(Date value) {
            addCriterion("CHECKDATE =", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotEqualTo(Date value) {
            addCriterion("CHECKDATE <>", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThan(Date value) {
            addCriterion("CHECKDATE >", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThanOrEqualTo(Date value) {
            addCriterion("CHECKDATE >=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThan(Date value) {
            addCriterion("CHECKDATE <", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThanOrEqualTo(Date value) {
            addCriterion("CHECKDATE <=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateIn(List<Date> values) {
            addCriterion("CHECKDATE in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotIn(List<Date> values) {
            addCriterion("CHECKDATE not in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateBetween(Date value1, Date value2) {
            addCriterion("CHECKDATE between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotBetween(Date value1, Date value2) {
            addCriterion("CHECKDATE not between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("CREATORID is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("CREATORID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("CREATORID =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("CREATORID <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("CREATORID >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORID >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("CREATORID <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("CREATORID <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("CREATORID like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("CREATORID not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("CREATORID in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("CREATORID not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("CREATORID between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("CREATORID not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreateformIsNull() {
            addCriterion("CREATEFORM is null");
            return (Criteria) this;
        }

        public Criteria andCreateformIsNotNull() {
            addCriterion("CREATEFORM is not null");
            return (Criteria) this;
        }

        public Criteria andCreateformEqualTo(String value) {
            addCriterion("CREATEFORM =", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotEqualTo(String value) {
            addCriterion("CREATEFORM <>", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformGreaterThan(String value) {
            addCriterion("CREATEFORM >", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEFORM >=", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformLessThan(String value) {
            addCriterion("CREATEFORM <", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformLessThanOrEqualTo(String value) {
            addCriterion("CREATEFORM <=", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformLike(String value) {
            addCriterion("CREATEFORM like", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotLike(String value) {
            addCriterion("CREATEFORM not like", value, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformIn(List<String> values) {
            addCriterion("CREATEFORM in", values, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotIn(List<String> values) {
            addCriterion("CREATEFORM not in", values, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformBetween(String value1, String value2) {
            addCriterion("CREATEFORM between", value1, value2, "createform");
            return (Criteria) this;
        }

        public Criteria andCreateformNotBetween(String value1, String value2) {
            addCriterion("CREATEFORM not between", value1, value2, "createform");
            return (Criteria) this;
        }

        public Criteria andUpdatoridIsNull() {
            addCriterion("UPDATORID is null");
            return (Criteria) this;
        }

        public Criteria andUpdatoridIsNotNull() {
            addCriterion("UPDATORID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatoridEqualTo(String value) {
            addCriterion("UPDATORID =", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotEqualTo(String value) {
            addCriterion("UPDATORID <>", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridGreaterThan(String value) {
            addCriterion("UPDATORID >", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATORID >=", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridLessThan(String value) {
            addCriterion("UPDATORID <", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridLessThanOrEqualTo(String value) {
            addCriterion("UPDATORID <=", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridLike(String value) {
            addCriterion("UPDATORID like", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotLike(String value) {
            addCriterion("UPDATORID not like", value, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridIn(List<String> values) {
            addCriterion("UPDATORID in", values, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotIn(List<String> values) {
            addCriterion("UPDATORID not in", values, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridBetween(String value1, String value2) {
            addCriterion("UPDATORID between", value1, value2, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatoridNotBetween(String value1, String value2) {
            addCriterion("UPDATORID not between", value1, value2, "updatorid");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("UPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("UPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("UPDATEDATE =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("UPDATEDATE <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("UPDATEDATE >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("UPDATEDATE <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATEDATE <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("UPDATEDATE in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("UPDATEDATE not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATEDATE not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdateformIsNull() {
            addCriterion("UPDATEFORM is null");
            return (Criteria) this;
        }

        public Criteria andUpdateformIsNotNull() {
            addCriterion("UPDATEFORM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateformEqualTo(String value) {
            addCriterion("UPDATEFORM =", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotEqualTo(String value) {
            addCriterion("UPDATEFORM <>", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformGreaterThan(String value) {
            addCriterion("UPDATEFORM >", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEFORM >=", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformLessThan(String value) {
            addCriterion("UPDATEFORM <", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformLessThanOrEqualTo(String value) {
            addCriterion("UPDATEFORM <=", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformLike(String value) {
            addCriterion("UPDATEFORM like", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotLike(String value) {
            addCriterion("UPDATEFORM not like", value, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformIn(List<String> values) {
            addCriterion("UPDATEFORM in", values, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotIn(List<String> values) {
            addCriterion("UPDATEFORM not in", values, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformBetween(String value1, String value2) {
            addCriterion("UPDATEFORM between", value1, value2, "updateform");
            return (Criteria) this;
        }

        public Criteria andUpdateformNotBetween(String value1, String value2) {
            addCriterion("UPDATEFORM not between", value1, value2, "updateform");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtIsNull() {
            addCriterion("WRITEOFFAMT is null");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtIsNotNull() {
            addCriterion("WRITEOFFAMT is not null");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtEqualTo(BigDecimal value) {
            addCriterion("WRITEOFFAMT =", value, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtNotEqualTo(BigDecimal value) {
            addCriterion("WRITEOFFAMT <>", value, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtGreaterThan(BigDecimal value) {
            addCriterion("WRITEOFFAMT >", value, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("WRITEOFFAMT >=", value, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtLessThan(BigDecimal value) {
            addCriterion("WRITEOFFAMT <", value, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("WRITEOFFAMT <=", value, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtIn(List<BigDecimal> values) {
            addCriterion("WRITEOFFAMT in", values, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtNotIn(List<BigDecimal> values) {
            addCriterion("WRITEOFFAMT not in", values, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WRITEOFFAMT between", value1, value2, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WRITEOFFAMT not between", value1, value2, "writeoffamt");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateIsNull() {
            addCriterion("WRITEOFFDATE is null");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateIsNotNull() {
            addCriterion("WRITEOFFDATE is not null");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateEqualTo(Date value) {
            addCriterion("WRITEOFFDATE =", value, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateNotEqualTo(Date value) {
            addCriterion("WRITEOFFDATE <>", value, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateGreaterThan(Date value) {
            addCriterion("WRITEOFFDATE >", value, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateGreaterThanOrEqualTo(Date value) {
            addCriterion("WRITEOFFDATE >=", value, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateLessThan(Date value) {
            addCriterion("WRITEOFFDATE <", value, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateLessThanOrEqualTo(Date value) {
            addCriterion("WRITEOFFDATE <=", value, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateIn(List<Date> values) {
            addCriterion("WRITEOFFDATE in", values, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateNotIn(List<Date> values) {
            addCriterion("WRITEOFFDATE not in", values, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateBetween(Date value1, Date value2) {
            addCriterion("WRITEOFFDATE between", value1, value2, "writeoffdate");
            return (Criteria) this;
        }

        public Criteria andWriteoffdateNotBetween(Date value1, Date value2) {
            addCriterion("WRITEOFFDATE not between", value1, value2, "writeoffdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 22 13:32:19 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XFWRITEOFFINFO
     *
     * @mbggenerated Fri Jul 22 13:32:19 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}