package ibp.repository.model;

public class IbpSbsAct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.IBP_SBS_ACT.PKID
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.IBP_SBS_ACT.ACTNUM
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    private String actnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.IBP_SBS_ACT.ACTNAM
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    private String actnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.IBP_SBS_ACT.STATUS
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIP.IBP_SBS_ACT.OPNDAT
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    private String opndat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.IBP_SBS_ACT.PKID
     *
     * @return the value of FIP.IBP_SBS_ACT.PKID
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.IBP_SBS_ACT.PKID
     *
     * @param pkid the value for FIP.IBP_SBS_ACT.PKID
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.IBP_SBS_ACT.ACTNUM
     *
     * @return the value of FIP.IBP_SBS_ACT.ACTNUM
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public String getActnum() {
        return actnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.IBP_SBS_ACT.ACTNUM
     *
     * @param actnum the value for FIP.IBP_SBS_ACT.ACTNUM
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public void setActnum(String actnum) {
        this.actnum = actnum == null ? null : actnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.IBP_SBS_ACT.ACTNAM
     *
     * @return the value of FIP.IBP_SBS_ACT.ACTNAM
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public String getActnam() {
        return actnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.IBP_SBS_ACT.ACTNAM
     *
     * @param actnam the value for FIP.IBP_SBS_ACT.ACTNAM
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public void setActnam(String actnam) {
        this.actnam = actnam == null ? null : actnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.IBP_SBS_ACT.STATUS
     *
     * @return the value of FIP.IBP_SBS_ACT.STATUS
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.IBP_SBS_ACT.STATUS
     *
     * @param status the value for FIP.IBP_SBS_ACT.STATUS
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIP.IBP_SBS_ACT.OPNDAT
     *
     * @return the value of FIP.IBP_SBS_ACT.OPNDAT
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public String getOpndat() {
        return opndat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIP.IBP_SBS_ACT.OPNDAT
     *
     * @param opndat the value for FIP.IBP_SBS_ACT.OPNDAT
     *
     * @mbggenerated Thu Nov 13 11:47:25 CST 2014
     */
    public void setOpndat(String opndat) {
        this.opndat = opndat == null ? null : opndat.trim();
    }
}